// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * 상세 주석 추가판 (한국어)
 *
 * 설명 요약:
 * - 이 파일은 Unframer로 생성된 Framer 컴포넌트의 빌드 출력물입니다.
 * - 원본 로직은 손대지 않고 주요 상수, 헬퍼 함수, 훅, 렌더 블록에 대해 한국어 주석을 추가했습니다.
 * - 주석은 컴포넌트 구조와 런타임 동작(프리로딩, 페처, 뷰포트 기반 지연 로딩, 호버 애니메이션 등)을 이해하는 데 집중합니다.
 *
 * 주의:
 * - 런타임 API(Unframer 관련 함수들)는 프로젝트 환경에서 제공됩니다.
 * - 자동 생성 파일이므로 원래는 수동 편집을 권장하지 않지만, 학습/리뷰 목적의 주석 추가 요청에 따라 주석만 삽입했습니다.
 */

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props
 *
 * Props 타입: 컴포넌트에서 받는 주요 속성들을 정의합니다.
 */

import { stdin_default } from "./chunks/chunk-FJDVB2KY.js"; // 외부(모듈)로부터 가져온 Smart/아이템 컴포넌트
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js"; // GoogleMaps 래퍼 컴포넌트
import { stdin_default as stdin_default2 } from "./chunks/chunk-U6ARRNOW.js"; // 네비게이션/헤더 등
import { routes } from "./chunks/chunk-RX5K52XN.js"; // 라우트 메타데이터

// virtual:info-cheong
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer"; // Framer/Unframer 컨텍스트 래퍼

// JSX runtime을 직접 사용 (Unframer 코드 생성 방식)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	Fetcher,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	usePrefetch,
	usePreloadQuery,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

/* ---------- 폰트 메타데이터 수집 ----------
 * getFonts는 각 모듈이 사용하는 폰트 메타를 수집합니다.
 * 나중에 addFonts로 컴포넌트에 등록됩니다.
 */
var Navigation3Fonts = getFonts(stdin_default2);
var GoogleMapsFonts = getFonts(GoogleMaps);
var DdFonts = getFonts(stdin_default);

/* ---------- 시리얼라이제이션 / variant 관련 상수 ---------- */
var serializationHash = "framer-04XbF"; // CSS scope 및 고유 식별자
var variantClassNames = {
	// variant identifier -> 클래스명 매핑 (useVariantState에서 사용)
	URq8NMD8r: "framer-v-uhzbp2",
};

/* ---------- motion 전환 및 transform 템플릿 ---------- */
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};

// transformTemplate1/2: SmartComponentScopedContainer나 motion 요소에 고유한 transform 템플릿을 제공.
// Framer가 변환 문자열을 조합하는 방식에 맞춰 템플릿을 반환합니다.
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;

/* ---------- 데이터 프리페치(프리로딩) 쿼리 정의 ----------
 * query 함수는 usePrefetch에 전달되어 선행 요청을 만들 때 사용됩니다.
 * 여기서는 외부 API `https://api.fetch.tools/location`을 요청하고,
 * 실패 시 사용될 fallbackValue(한글: "청주")를 지정합니다.
 */
var query = (prefetch) =>
	prefetch({
		cacheDuration: 0,
		credentials: "same-origin",
		errorFallbackValue: "Error",
		fallbackValue: "\uCCAD\uC8FC", // UTF-16 escape for "청주"
		resultKeyPath: "",
		resultOutputType: "string",
		url: `https://api.fetch.tools/location`,
	});

/* 간단한 헬퍼: 값이 문자열이면 그대로, 아니면 String() 호출 */
var toString = (value) => {
	return typeof value === "string" ? value : String(value);
};

/* 다른 전환 설정 - tween */
var transition2 = {
	delay: 0,
	duration: 0.45,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};

/* 호버/애니메이션 기본 동작 정의(whileHover 같은 곳에서 사용) */
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1.2,
	skewX: 0,
	skewY: 0,
	transition: transition2,
};

var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`;

/* Transition: MotionConfigContext의 transition을 병합해 하위에 전달하는 래퍼 */
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};

/* preload: 사전 로딩 작업을 나열한다. 현재는 query(prefetch) 하나 뿐 */
var preload = (prequery, prefetch, props) => Promise.all([query(prefetch)]);
var preloadStatements = {
	// variant id -> 프리로드 함수 매핑
	URq8NMD8r: preload,
};

/* ---------- 로딩 변형 훅 ----------
 * useLoadingVariant:
 * - variant, gestures, clearLoadingVariant, setGestureState 등을 받아
 * - variant가 바뀔 때 (혹은 제스처의 loading이 활성화될 때) 정의된 preloadStatements를 실행
 * - 성공 시 clearLoadingVariant 호출, 실패 시 setGestureState({ isError: true }) 호출
 */
var useLoadingVariant = (
	variant,
	gestures,
	clearLoadingVariant,
	setGestureState,
	props,
) => {
	const prequery = usePreloadQuery();
	const prefetch = usePrefetch();
	React.useEffect(() => {
		const promise = preloadStatements[variant];
		if (!promise || !gestures?.[variant]?.loading) return;
		promise(prequery, prefetch, props)
			.then(() => clearLoadingVariant())
			.catch(() =>
				setGestureState({
					isError: true,
				}),
			);
	}, [variant]);
};

var Variants = motion.create(React.Fragment);

/* getProps: 프롭 중 일부(height,id,width 등)를 제외하고 나머지를 반환 */
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};

/* layoutDependency 생성 헬퍼: variants 배열과 props.layoutDependency를 결합 */
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};

/* ---------- 메인 컴포넌트 ---------- */
/* Component: forwardRef로 만들어진 루트 컴포넌트 */
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	// ref 바인딩 처리(부모 ref가 없으면 내부 fallbackRef 사용)
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;

	// 고유 layoutId 생성 (React.useId)
	const defaultLayoutId = React.useId();

	// 로케일 훅: 현재 로케일 및 변경 함수
	const { activeLocale, setLocale } = useLocaleInfo();

	// 현재 뷰포트(스크롤 위치, 높이 등) 정보 (이미지 지연 로딩 등에 사용)
	const componentViewport = useComponentViewport();

	// style/className/layoutId/variant 제외한 나머지 props
	const { style, className, layoutId, variant, ...restProps } = getProps(
		props,
	);

	// useVariantState: Framer 변형(variant) 관리 훅
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "URq8NMD8r",
		ref: refBinding,
		variant,
		variantClassNames,
	});

	// layout dependency key 생성
	const layoutDependency = createLayoutDependency(props, variants);

	// scoping class names (CSS scoping용)
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);

	// 로딩 변형 훅 사용: baseVariant가 로딩 제스처를 요구하면 프리로드 실행
	useLoadingVariant(baseVariant, void 0, clearLoadingGesture, setGestureState);

	/* ---------- 렌더 트리 ---------- */
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			{/* Variants로 변형(variant) 상태를 애니메이션 컨텍스트에 전달 */}
			<Variants animate={variants} initial={false}>
				{/* Transition 제공: motion의 transition 설정을 하위에 전달 */}
				<Transition value={transition1}>
					{/* 최상위 컨테이너: 제스처 핸들러, 클래스, layoutId 등 부착 */}
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-uhzbp2",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"URq8NMD8r"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{/* 최상단 고정 영역: 뷰포트 제공자 (컴포넌트 상단에 고정되는 헤더/네비게이션 등에 사용) */}
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-1h541yu-container"}
								layoutDependency={layoutDependency}
								layoutId={"tp8LX8Tyv-container"}
								nodeId={"tp8LX8Tyv"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								transformTemplate={transformTemplate1}
							>
								{/* 헤더/네비게이션 구성 요소 (외부 모듈) */}
								{_jsx(stdin_default2, {
									height: "100%",
									id: "tp8LX8Tyv",
									layoutId: "tp8LX8Tyv",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 배너/배경 이미지: getLoadingLazyAtYPosition로 뷰포트 기반 lazy 로딩 */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 166,
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-b97qi7"}
							layoutDependency={layoutDependency}
							layoutId={"C_03sDKOZ"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						{/* Fetcher: 비동기 요청을 수행하고 결과를 받아 하위 컴포넌트(GoogleMaps)에 전달한다.
                         * - disabled={isLoading}으로 variant 로딩 중이면 요청을 비활성화
                         * - requests는 배열(여러 요청 가능). 여기선 하나의 위치 API 호출.
                         * - fetchResult는 콜백에 배열 형태로 전달되며, GoogleMaps에는 fetchResult[0]을 사용
                         */}
						<Fetcher
							disabled={isLoading}
							requests={[
								{
									cacheDuration: 0,
									credentials: "same-origin",
									errorFallbackValue: "Error",
									fallbackValue: "\uCCAD\uC8FC", // "청주"
									resultKeyPath: "",
									resultOutputType: "string",
									url: `https://api.fetch.tools/location`,
								},
							]}
						>
							{(fetchResult) => (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-w6wdje-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"ln5qt0eEM-container"}
										nodeId={"ln5qt0eEM"}
										rendersWithMotion={true}
										scopeId={"CDDWVZVDv"}
									>
										{/* GoogleMaps: Fetcher의 결과(fetchResult[0])를 좌표 문자열로 전달 */}
										<GoogleMaps
											borderRadius={18}
											bottomLeftRadius={18}
											bottomRightRadius={18}
											coordinates={toString(fetchResult[0])}
											height={"100%"}
											id={"ln5qt0eEM"}
											isMixedBorderRadius={false}
											layoutId={"ln5qt0eEM"}
											style={{
												height: "100%",
												width: "100%",
											}}
											topLeftRadius={18}
											topRightRadius={18}
											width={"100%"}
											zoom={15}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</Fetcher>

						{/* 이후로는 배너 위에 겹쳐진 이미지/레이블/호버 가능한 컴포넌트들이 연속으로 배치됨.
                         * 구조적으로 반복되는 패턴:
                         * - Image (배경 또는 썸네일)
                         * - gradient overlay (motion.div로 만든 어둡게 처리된 영역)
                         * - RichText (레이블 텍스트)
                         * - SmartComponentScopedContainer (사용자 정의 모듈을 포함, whileHover 애니메이션 적용)
                         *
                         * 공통 포인트:
                         * - getLoadingLazyAtYPosition(componentViewport?.y + offset)로 lazy 로딩 임계값을 계산
                         * - whileHover에 정의된 'animation' 객체로 호버 시 스케일 업 / 트랜지션 적용
                         * - transformTemplate 속성은 특정 요소의 transform 합성 규칙을 맞추기 위해 사용
                         */}

						<motion.div
							className={"framer-put5xq"}
							layoutDependency={layoutDependency}
							layoutId={"hoC4q_zMO"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-16ry7eq"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"IKidxybuH"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 연속된 이미지와 레이블들이 반복됨 (레이아웃 위치 및 z-index로 화면 상 특정 위치에 배치) */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 166,
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-1wypw3a"}
							layoutDependency={layoutDependency}
							layoutId={"nCOxUDWTF"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						<motion.div
							className={"framer-1vcy7gs"}
							layoutDependency={layoutDependency}
							layoutId={"q5_GNwNXW"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ku8jg2"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"MpSrDR8Vu"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 166,
								),
								pixelHeight: 800,
								pixelWidth: 800,
								sizes: "212px",
								src: "https://framerusercontent.com/images/1Oo5DWNUKonP48Tbn7TiAbfB1Q.jpg?width=800&height=800",
								srcSet:
									"https://framerusercontent.com/images/1Oo5DWNUKonP48Tbn7TiAbfB1Q.jpg?scale-down-to=512&width=800&height=800 512w,https://framerusercontent.com/images/1Oo5DWNUKonP48Tbn7TiAbfB1Q.jpg?width=800&height=800 800w",
							}}
							className={"framer-1b4u959"}
							layoutDependency={layoutDependency}
							layoutId={"oUbGanKrP"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						{/* SmartComponentScopedContainer: 내부에 사용자 컴포넌트(stdin_default)를 포함하고 whileHover 애니메이션 적용 */}
						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={(componentViewport?.y || 0) + 334}
						>
							<SmartComponentScopedContainer
								className={"framer-1t0cx7t-container"}
								data-framer-name={"\uB8E8\uD2B8\uCEE4\uD53C"} // "루트컴포넌트" 같은 이름(UTF-16)
								layoutDependency={layoutDependency}
								layoutId={"xVAUf87Ya-container"}
								name={"\uB8E8\uD2B8\uCEE4\uD53C"}
								nodeId={"xVAUf87Ya"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation} // hover 애니메이션 적용
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "xVAUf87Ya",
									layoutId: "xVAUf87Ya",
									name: "\uB8E8\uD2B8\uCEE4\uD53C",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "fGuAYwA2U",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 이미지 / 마커 / 라벨들이 반복적으로 배치됨: 이후 코드에서 같은 패턴이 계속됨 */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 166,
								),
								pixelHeight: 258,
								pixelWidth: 195,
								sizes: "212px",
								src: "https://framerusercontent.com/images/7Aa3QWWgrc44siDnL2ZFX31AE.jpg?width=195&height=258",
							}}
							className={"framer-vwpdgw"}
							layoutDependency={layoutDependency}
							layoutId={"jlfAoAwy9"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						<motion.div
							className={"framer-1vv3tvm"}
							layoutDependency={layoutDependency}
							layoutId={"VGgHwPeM7"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.76) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* 같은 패턴이 계속 반복됨: 각 요소는 화면 특정 위치에 배치된 '카드' 또는 '마커'를 구성 */}
						<motion.div
							className={"framer-2mrnx5"}
							layoutDependency={layoutDependency}
							layoutId={"FzZJFaQPR"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.76) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={(componentViewport?.y || 0) + 334}
						>
							<SmartComponentScopedContainer
								className={"framer-1j2vj2j-container"}
								data-framer-name={"\uD2B8\uB9AC\uBE14\uB9C1"} // "트리블링" 등 이름
								layoutDependency={layoutDependency}
								layoutId={"Iizc88YtG-container"}
								name={"\uD2B8\uB9AC\uBE14\uB9C1"}
								nodeId={"Iizc88YtG"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "Iizc88YtG",
									layoutId: "Iizc88YtG",
									name: "\uD2B8\uB9AC\uBE14\uB9C1",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "sjxUsFAxU",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 레이블 텍스트 (여러 개) */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-yrdpyk"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"x3_U3bO4u"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"TREE"}
									<motion.br />
									{".BRING"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 이후 블록은 반복되는 마커/이미지/레이블 패턴: 위치 계산에 componentViewport 값을 사용해 lazy 로딩과 애니메이션을 제어 */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 968) * 0.5433884297520664 -
											106),
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-4lqp15"}
							layoutDependency={layoutDependency}
							layoutId={"KyWgg6IlU"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
							transformTemplate={transformTemplate2}
						/>

						<motion.div
							className={"framer-1753zru"}
							layoutDependency={layoutDependency}
							layoutId={"cMVdwKTEJ"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* 레이블 텍스트(반복) */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ageg4m"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"UboDEQI8k"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 추가 이미지/레이블/호버 가능한 항목들이 더 이어짐... */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 968) * 0.5433884297520664 -
											106),
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-t7jrkx"}
							layoutDependency={layoutDependency}
							layoutId={"RcR0jUTSh"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
							transformTemplate={transformTemplate2}
						/>

						<motion.div
							className={"framer-1agmgu9"}
							layoutDependency={layoutDependency}
							layoutId={"Dv2slzfP_"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* 레이블 텍스트 */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-16ulvkz"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"sLMiGbZwT"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 968) * 0.5433884297520664 -
											106),
								),
								pixelHeight: 312,
								pixelWidth: 270,
								sizes: "212px",
								src: "https://framerusercontent.com/images/1Am9n3n5oQalVmC3yvWGhexGes.jpg?width=270&height=312",
							}}
							className={"framer-5r67op"}
							layoutDependency={layoutDependency}
							layoutId={"YY6Po5BHO"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
							transformTemplate={transformTemplate2}
						/>

						<motion.div
							className={"framer-1g4ccq1"}
							layoutDependency={layoutDependency}
							layoutId={"poD23OKq9"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.71) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* SmartComponentScopedContainer + 내부 컴포넌트(호버 애니메이션 포함) - 예: '청남대' */}
						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 968) -
								374
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1rj230f-container"}
								data-framer-name={"\uCCAD\uB0A8\uB300"} // "청남대"
								layoutDependency={layoutDependency}
								layoutId={"g1f7RQOIO-container"}
								name={"\uCCAD\uB0A8\uB300"}
								nodeId={"g1f7RQOIO"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "g1f7RQOIO",
									layoutId: "g1f7RQOIO",
									name: "\uCCAD\uB0A8\uB300",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "Lz6sZz61R",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 레이블/이미지 패턴 반복 (여러 지점) */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-44ch9c"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"G3Q0Dr6Ov"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"CHEON"}
									<motion.br />
									{"GNAM"}
									<motion.br />
									{"DAE"}
								</motion.p>
							</React.Fragment>
						</RichText>

						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 968) * 0.5433884297520664 -
											106),
								),
								pixelHeight: 422,
								pixelWidth: 350,
								sizes: "212px",
								src: "https://framerusercontent.com/images/CbGmQkQ6poL2zkOrp5OU60ZFPk.jpg?width=350&height=422",
							}}
							className={"framer-njcipa"}
							layoutDependency={layoutDependency}
							layoutId={"u4YbzPMe6"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
							transformTemplate={transformTemplate2}
						/>

						{/* 또 다른 SmartComponentScopedContainer (호버로 애니메이션) */}
						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 968) -
								374
							}
						>
							<SmartComponentScopedContainer
								className={"framer-9ixslc-container"}
								data-framer-name={"\uBA85\uC554\uD0C0\uC6CC"} // "명암타워" 등
								layoutDependency={layoutDependency}
								layoutId={"gMklgWRDg-container"}
								name={"\uBA85\uC554\uD0C0\uC6CC"}
								nodeId={"gMklgWRDg"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "gMklgWRDg",
									layoutId: "gMklgWRDg",
									name: "\uBA85\uC554\uD0C0\uC6CC",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "OYKnf4EQ7",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 이후에도 동일한 패턴의 이미지/레이블/호버 컴포넌트가 연속 */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 968) -
										291,
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-6d4p0o"}
							layoutDependency={layoutDependency}
							layoutId={"EQRQSch4B"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						<motion.div
							className={"framer-wjk3mi"}
							layoutDependency={layoutDependency}
							layoutId={"O5cTiPJDn"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* 레이블 */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-5ifmdl"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"kjaM2BHj3"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 968) -
										291,
								),
								pixelHeight: 458,
								pixelWidth: 1178,
								sizes: "212px",
								src: "https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458",
								srcSet:
									"https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=512&width=1178&height=458 512w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?scale-down-to=1024&width=1178&height=458 1024w,https://framerusercontent.com/images/LBcEvsNiqzFAPcOWUC2V9sIS08A.jpg?width=1178&height=458 1178w",
							}}
							className={"framer-1f6s7gj"}
							layoutDependency={layoutDependency}
							layoutId={"E8cKDcr0h"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						<motion.div
							className={"framer-5491yu"}
							layoutDependency={layoutDependency}
							layoutId={"iWrA32jcO"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.65) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* SmartComponentScopedContainer (예: '가로수길') - 호버 애니메이션 */}
						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 968) -
								123
							}
						>
							<SmartComponentScopedContainer
								className={"framer-8l7wt2-container"}
								data-framer-name={"\uAC00\uB85C\uC218\uAE38"} // "가로수길"
								layoutDependency={layoutDependency}
								layoutId={"r6DTgeKUh-container"}
								name={"\uAC00\uB85C\uC218\uAE38"}
								nodeId={"r6DTgeKUh"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "r6DTgeKUh",
									layoutId: "r6DTgeKUh",
									name: "\uAC00\uB85C\uC218\uAE38",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "FvjsO6beA",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 레이블 텍스트 */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-b9kow6"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"Hq5U1uX5V"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"YEONGGEUMJEONG"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 여러 이미지/레이블/마커가 추가로 배치됨 (생성된 CSS의 위치/크기 규칙에 의해 화면에 배치됨) */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 968) -
										291,
								),
								pixelHeight: 640,
								pixelWidth: 960,
								sizes: "212px",
								src: "https://framerusercontent.com/images/CRDGEq7SxmBECv37s4j6ct3qi4k.jpg?width=960&height=640",
								srcSet:
									"https://framerusercontent.com/images/CRDGEq7SxmBECv37s4j6ct3qi4k.jpg?scale-down-to=512&width=960&height=640 512w,https://framerusercontent.com/images/CRDGEq7SxmBECv37s4j6ct3qi4k.jpg?width=960&height=640 960w",
							}}
							className={"framer-qto7qd"}
							layoutDependency={layoutDependency}
							layoutId={"aqiN05Scs"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						/>

						{/* 다음 SmartComponentScopedContainer (호버 포함) */}
						<ComponentViewportProvider
							height={29}
							width={"77px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 968) -
								123
							}
						>
							<SmartComponentScopedContainer
								className={"framer-jqj0d-container"}
								data-framer-name={"\uB300\uCCAD\uD638\uC218"} // "대청호수" 등
								layoutDependency={layoutDependency}
								layoutId={"e2QCQssDO-container"}
								name={"\uB300\uCCAD\uD638\uC218"}
								nodeId={"e2QCQssDO"}
								rendersWithMotion={true}
								scopeId={"CDDWVZVDv"}
								whileHover={animation}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "e2QCQssDO",
									layoutId: "e2QCQssDO",
									name: "\uB300\uCCAD\uD638\uC218",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "V7Fdg_4Mh",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* 이미지와 내부 SmartComponentScopedContainer의 조합(예시) */}
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(componentViewport?.height || 968) -
										291,
								),
								pixelHeight: 512,
								pixelWidth: 793,
								sizes: "212px",
								src: "https://framerusercontent.com/images/aEk9eRf5cEuJjwUX9WsWSRY6sM.jpg?width=793&height=512",
								srcSet:
									"https://framerusercontent.com/images/aEk9eRf5cEuJjwUX9WsWSRY6sM.jpg?scale-down-to=512&width=793&height=512 512w,https://framerusercontent.com/images/aEk9eRf5cEuJjwUX9WsWSRY6sM.jpg?width=793&height=512 793w",
							}}
							className={"framer-18bywn3"}
							layoutDependency={layoutDependency}
							layoutId={"xH954hPQ0"}
							style={{
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
							}}
						>
							{/* Image 내부에 SmartComponentScopedContainer를 중첩해 특정 오프셋에서 모듈 표시 */}
							<ComponentViewportProvider
								height={29}
								width={"77px"}
								y={
									(componentViewport?.y || 0) +
									(componentViewport?.height || 968) -
									291 +
									212 -
									44
								}
							>
								<SmartComponentScopedContainer
									className={"framer-k4qamv-container"}
									layoutDependency={layoutDependency}
									layoutId={"FsaweczmB-container"}
									nodeId={"FsaweczmB"}
									rendersWithMotion={true}
									scopeId={"CDDWVZVDv"}
									whileHover={animation}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "FsaweczmB",
										layoutId: "FsaweczmB",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "FvjsO6beA",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</Image>

						{/* 레이블: ROOT COFFEE 등 */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ktxwyy"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"XAAM5imxw"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"ROOT"}
									<motion.br />
									{"COFFEE"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 화면 오른쪽/아래로 이어지는 여러 gradient/레이블 패턴들... */}
						<motion.div
							className={"framer-c4l72b"}
							layoutDependency={layoutDependency}
							layoutId={"u6p95EN57"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.76) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>
						<motion.div
							className={"framer-1sgrbe4"}
							layoutDependency={layoutDependency}
							layoutId={"f1V1X9QSQ"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.76) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>
						<motion.div
							className={"framer-t5sdiz"}
							layoutDependency={layoutDependency}
							layoutId={"JfZ5Ba2Oo"}
							style={{
								background:
									"linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.76) 100%)",
								borderBottomRightRadius: 14,
								borderTopRightRadius: 14,
								rotate: -90,
							}}
						/>

						{/* 페이지 하단/오른쪽에 배치된 여러 텍스트 레이블(예: MYONGAM TOWER 등) */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1klns65"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"nkHrbC34t"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"MYONGAM"}
									<motion.br />
									{"TOWER"}
								</motion.p>
							</React.Fragment>
						</RichText>

						{/* 다른 레이블들 */}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1yj9sce"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"crnuduGIT"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"CHEONGJU"}
									<motion.br />
									{"GAROSUGIL"}
								</motion.p>
							</React.Fragment>
						</RichText>

						<RichText
							__fromCanvasComponent={true}
							className={"framer-lvt33h"}
							fonts={["BI;DT Getai Grotesk Display /Black/v0"]}
							layoutDependency={layoutDependency}
							layoutId={"SX1bWfswZ"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Qkk7RFQgR2V0YWkgR3JvdGVzayBEaXNwbGF5IC9CbGFjay92MA==",
										"--framer-font-family":
											'"DT Getai Grotesk Display ", sans-serif',
										"--framer-font-size": "18px",
										"--framer-font-weight": "900",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
									}}
								>
									{"DAECHEONG"}
									<motion.br />
									{"LAKE"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});

/* ---------- CSS 스코핑 배열 (Unframer가 생성한 원본 스타일) ---------- */
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-04XbF.framer-1hhmp5c, .framer-04XbF .framer-1hhmp5c { display: block; }",
	".framer-04XbF.framer-uhzbp2 { height: 968px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1980px; }",
	".framer-04XbF .framer-1h541yu-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-04XbF .framer-b97qi7, .framer-04XbF .framer-1b4u959 { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 212px); left: 1471px; position: absolute; top: 166px; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-w6wdje-container { bottom: 0px; flex: none; height: 880px; left: 29px; position: absolute; width: 1397px; z-index: 1; }",
	".framer-04XbF .framer-put5xq, .framer-04XbF .framer-2mrnx5 { flex: none; height: 212px; left: 1524px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 113px; width: 106px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-04XbF .framer-16ry7eq { flex: none; height: 54px; left: 1485px; position: absolute; top: 195px; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-1wypw3a, .framer-04XbF .framer-vwpdgw { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 212px); left: 1725px; position: absolute; top: 166px; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-1vcy7gs, .framer-04XbF .framer-1vv3tvm { flex: none; height: 212px; left: 1778px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 113px; width: 106px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-1ku8jg2 { flex: none; height: 54px; left: 1739px; position: absolute; top: 195px; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-1t0cx7t-container { flex: none; height: 29px; left: 1590px; position: absolute; top: 334px; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-1j2vj2j-container { flex: none; height: 29px; left: 1844px; position: absolute; top: 334px; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-yrdpyk { flex: none; height: 54px; left: 1740px; position: absolute; top: 183px; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-4lqp15, .framer-04XbF .framer-5r67op { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 212px); left: 1471px; position: absolute; top: 54%; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-1753zru, .framer-04XbF .framer-1g4ccq1 { flex: none; height: 212px; left: 1524px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: calc(48.86363636363639% - 212px / 2); width: 106px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-04XbF .framer-ageg4m, .framer-04XbF .framer-44ch9c { flex: none; height: 54px; left: 1486px; position: absolute; top: calc(47.933884297520684% - 54px / 2); white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-t7jrkx, .framer-04XbF .framer-njcipa { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 212px); left: 1725px; position: absolute; top: 54%; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-1agmgu9, .framer-04XbF .framer-c4l72b { flex: none; height: 212px; left: 1778px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: calc(48.86363636363639% - 212px / 2); width: 106px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-04XbF .framer-16ulvkz, .framer-04XbF .framer-1klns65 { flex: none; height: 54px; left: 1740px; position: absolute; top: calc(47.933884297520684% - 54px / 2); white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-1rj230f-container { bottom: 345px; flex: none; height: 29px; left: 1590px; position: absolute; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-9ixslc-container { bottom: 345px; flex: none; height: 29px; left: 1850px; position: absolute; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-6d4p0o, .framer-04XbF .framer-qto7qd { aspect-ratio: 1 / 1; bottom: 79px; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 212px); left: 1471px; position: absolute; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-wjk3mi, .framer-04XbF .framer-t5sdiz { bottom: 132px; flex: none; height: 212px; left: 1524px; overflow: var(--framer-overflow-clip-fallback, clip); position: absolute; width: 106px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-04XbF .framer-5ifmdl, .framer-04XbF .framer-lvt33h { bottom: 220px; flex: none; height: 54px; left: 1486px; position: absolute; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-1f6s7gj, .framer-04XbF .framer-18bywn3 { aspect-ratio: 1 / 1; bottom: 79px; flex: none; height: var(--framer-aspect-ratio-supported, 212px); left: 1725px; position: absolute; width: 212px; z-index: 1; }",
	".framer-04XbF .framer-5491yu, .framer-04XbF .framer-1sgrbe4 { bottom: 132px; flex: none; height: 212px; left: 1778px; overflow: var(--framer-overflow-clip-fallback, clip); position: absolute; width: 106px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-04XbF .framer-8l7wt2-container { bottom: 94px; flex: none; height: 29px; left: 1844px; position: absolute; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-b9kow6, .framer-04XbF .framer-1yj9sce { bottom: 220px; flex: none; height: 54px; left: 1740px; position: absolute; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-04XbF .framer-jqj0d-container { bottom: 94px; flex: none; height: 29px; left: 1590px; position: absolute; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-k4qamv-container { bottom: 15px; flex: none; height: 29px; position: absolute; right: 10px; width: 77px; will-change: var(--framer-will-change-effect-override, transform); z-index: 1; }",
	".framer-04XbF .framer-1ktxwyy { flex: none; height: 54px; left: 1486px; position: absolute; top: 183px; white-space: pre-wrap; width: 153px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
];

var FramerCDDWVZVDv = withCSS(Component, css, "framer-04XbF");
var stdin_default3 = FramerCDDWVZVDv;
FramerCDDWVZVDv.displayName = "info_cheong";
FramerCDDWVZVDv.defaultProps = {
	height: 968,
	width: 1980,
};

/* ---------- 폰트 등록 ----------
 * addFonts로 컴포넌트에 사용할 폰트들을 등록합니다.
 * - Navigation3Fonts / GoogleMapsFonts / DdFonts 는 위에서 getFonts로 수집된 폰트 메타데이터입니다.
 */
addFonts(
	FramerCDDWVZVDv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "DT Getai Grotesk Display ",
					source: "builtIn",
					style: "normal",
					uiFamilyName: "DT Getai Grotesk Display ",
					url: "https://framerusercontent.com/assets/EAkArLXTcvLC9Yy2BsWC7WSahM.woff2",
					weight: "900",
				},
			],
		},
		...Navigation3Fonts,
		...GoogleMapsFonts,
		...DdFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:info-cheong
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};

/**
 * ComponentWithRoot: ContextProviders로 routes, siteId, locale 등을 주입한 최상위 래퍼
 * - 실제로 외부에서 import할 때는 이 래퍼를 통해 Context가 제공됩니다.
 */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}

/**
 * ComponentWithRoot.Responsive:
 * - WithFramerBreakpoints를 사용해 반응형 브레이크포인트에 맞춰 variants를 적용할 수 있는 래퍼
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};

/* 원본 컴포넌트의 정적 속성(예: displayName, defaultProps 등)을 래퍼에 병합 */
Object.assign(ComponentWithRoot, stdin_default3);
var info_cheong_default = ComponentWithRoot;
export { info_cheong_default as default };