// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * 상세 주석 추가판
 *
 * 원본 파일의 동작을 그대로 유지하되 각 주요 변수, 함수, 컴포넌트와 렌더 트리의 역할을
 * 이해하기 쉽도록 한국어 주석을 최대한 세세하게 추가했습니다.
 */

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * }} Props
 *
 * Props 타입 정의: 컴포넌트가 받을 수 있는 주요 속성들을 명시합니다.
 * (원본 코드의 타입 힌트 유지)
 */

import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:info
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// 외부 모듈에서 JSX runtime을 직접 사용 (Unframer 코드 생성 방식)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

/* ---------- 폰트 로딩 관련 ---------- */
// Unframer가 생성한 폰트 집합을 가져옵니다. 컴포넌트에서 사용하는 가변 폰트들을 관리.
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);

/* serialization / variant 관련 상수들 */
var serializationHash = "framer-4AkQ8";
var variantClassNames = {
	// 변형(variant) 이름과 클래스 매핑. useVariantState에서 사용됨.
	F3whWOZ8Q: "framer-v-1abb9m3",
};

/* 기본 전환(transition) 설정: motion 애니메이션에서 사용 */
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};

/* Transition 컴포넌트
 * MotionConfigContext의 값을 병합하여 하위에 전달합니다.
 * - value가 제공되면 그 값을 우선 사용
 * - 내부적으로 context 값과 transition을 합쳐 다시 Provider로 감쌉니다.
 */
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};

/* Variants: motion에서 Fragment형태로 변형 애니메이션을 묶기 위해 생성 */
var Variants = motion.create(React.Fragment);

/* getProps:
 * 원본 props에서 height, width, id 등 일부를 제거하고 나머지를 반환합니다.
 * (원본 코드가 layout 관련 속성들을 내부에서 재구성하기 위해 사용)
 */
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};

/* layoutDependency 생성 헬퍼
 * - props.layoutDependency가 있으면 variants.join("-") + layoutDependency로 결합
 * - 없으면 단순히 variants.join("-") 반환
 * layoutDependency는 레이아웃 의존성을 고유하게 만드는데 사용됩니다.
 */
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};

/* ---------- 메인 컴포넌트 정의 ---------- */
/**
 * Component: Unframer로 생성된 Framer 컴포넌트의 루트 구현
 * - forwardRef로 ref 바인딩을 지원
 * - 내부적으로 여러 훅(useLocaleInfo, useComponentViewport, useVariantState 등)을 사용
 */
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	// ref 바인딩: 전달된 ref 없으면 내부 fallbackRef 사용
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;

	// React 18의 useId로 기본 layoutId 생성 (고유 ID)
	const defaultLayoutId = React.useId();

	// locale 제어 훅: 현재 활성 로케일과 변경 함수 제공
	const { activeLocale, setLocale } = useLocaleInfo();

	// 현재 컴포넌트 뷰포트(스크롤/뷰포지션) 정보 제공
	const componentViewport = useComponentViewport();

	// props에서 외부 스타일/클래스/variant 관련만 추출
	const { style, className, layoutId, variant, ...restProps } = getProps(
		props,
	);

	// useVariantState: Unframer가 생성한 상태 훅
	// - variant 관리, 제스처, 애니메이션 상태 등 제공
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "F3whWOZ8Q",
		ref: refBinding,
		variant,
		variantClassNames,
	});

	// layoutDependency: 같은 layoutId에 대한 의존성 키
	const layoutDependency = createLayoutDependency(props, variants);

	// 공유 스타일 클래스명(확장 가능)
	const sharedStyleClassNames = [];

	// scopingClassNames: serialization hash + 공유 클래스 -> CSS scoping용
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);

	/* ---------- 렌더 트리 시작 ---------- */
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			{/* Variants로 애니메이션 상태를 묶음 */}
			<Variants animate={variants} initial={false}>
				{/* Transition Provider: motion transition 설정을 하위에 적용 */}
				<Transition value={transition1}>
					{/* 최상위 컨테이너: motion.div로 변형/제스처/클래스 등을 적용 */}
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1abb9m3",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"F3whWOZ8Q"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{/* 최상단 고정 영역: ComponentViewportProvider로 뷰포트 높이/너비 전달 */}
						<ComponentViewportProvider
							height={67}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							{/* SmartComponentScopedContainer: 내부 캔버스/스코프 처리용 래퍼 */}
							<SmartComponentScopedContainer
								className={"framer-13jqi1c-container"}
								layoutDependency={layoutDependency}
								layoutId={"gNhDx_IWZ-container"}
								nodeId={"gNhDx_IWZ"}
								rendersWithMotion={true}
								scopeId={"LduaWW2WS"}
							>
								{/* stdin_default는 Unframer가 생성한 네비게이션/헤더 컴포넌트 등 */}
								{_jsx(stdin_default, {
									height: "100%",
									id: "gNhDx_IWZ",
									layoutId: "gNhDx_IWZ",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>

						{/* Hero 영역 (흰 배경) */}
						<motion.div
							className={"framer-b6o5kk"}
							data-framer-name={"Hero"}
							layoutDependency={layoutDependency}
							layoutId={"jm1fyFSQY"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
						>
							{/* 타이틀 블록 */}
							<motion.div
								className={"framer-1tos9uf"}
								layoutDependency={layoutDependency}
								layoutId={"rpeunIPjL"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-l0nmj9"}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"c2WyfA_d5"}
									style={{
										"--extracted-w4030y":
											'"opsz" 32, "wght" 700',
										"--framer-link-text-color":
											"rgb(0, 153, 255)",
										"--framer-link-text-decoration":
											"underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-open-type-features":
													"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
												"--framer-font-size": "40px",
												"--framer-font-variation-axes":
													'var(--extracted-w4030y, "opsz" 32, "wght" 700)',
												"--framer-letter-spacing":
													"-0.04em",
												"--framer-line-height": "1em",
												"--framer-text-alignment":
													"center",
											}}
										>
											{
												"\uD2B8\uB9BD\uCE90\uCC98\uC640 \uD568\uAED8 \uC5EC\uD589\uC744 \uC990\uAE30\uC138\uC694"
											}
											{/* 위 텍스트는 한글로 '트릭카처와 함께 여행을 즐기세요' (UTF-16 이스케이프 문자열) */}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>

							{/* Header 블록: 배경 회색, 내부에 Slideshow (모듈 외부 컴포넌트) 포함 */}
							<motion.div
								className={"framer-1rheogc"}
								data-framer-name={"Header"}
								layoutDependency={layoutDependency}
								layoutId={"WumYmq113"}
								style={{
									backgroundColor: "rgb(245, 245, 245)",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-4f17g5-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"n4_HdxCfC-container"}
										nodeId={"n4_HdxCfC"}
										rendersWithMotion={true}
										scopeId={"LduaWW2WS"}
									>
										{/* Slideshow 컴포넌트: 다양한 옵션(화살표, 페이드, 간격 등)을 props로 전달 */}
										<Slideshow
											alignment={"center"}
											arrowOptions={{
												arrowFill:
													"rgba(0, 0, 0, 0.2)",
												arrowGap: 10,
												arrowPadding: 20,
												arrowPaddingBottom: 0,
												arrowPaddingLeft: 0,
												arrowPaddingRight: 0,
												arrowPaddingTop: 0,
												arrowPosition: "auto",
												arrowRadius: 40,
												arrowShouldFadeIn: false,
												arrowShouldSpace: true,
												arrowSize: 40,
												showMouseControls: true,
											}}
											autoPlayControl={true}
											borderRadius={0}
											direction={"left"}
											dragControl={false}
											effectsOptions={{
												effectsHover: true,
												effectsOpacity: 1,
												effectsPerspective: 1200,
												effectsRotate: 0,
												effectsScale: 1,
												playOffscreen: false,
											}}
											fadeOptions={{
												fadeAlpha: 0,
												fadeContent: false,
												fadeInset: 0,
												fadeWidth: 25,
												overflow: false,
											}}
											gap={10}
											height={"100%"}
											id={"n4_HdxCfC"}
											intervalControl={1.5}
											itemAmount={1}
											layoutId={"n4_HdxCfC"}
											padding={0}
											paddingBottom={0}
											paddingLeft={0}
											paddingPerSide={false}
											paddingRight={0}
											paddingTop={0}
											progressOptions={{
												dotsActiveOpacity: 1,
												dotsBackground:
													"rgba(0, 0, 0, 0.2)",
												dotsBlur: 0,
												dotsFill: "rgb(255, 255, 255)",
												dotsGap: 10,
												dotsInset: 10,
												dotSize: 10,
												dotsOpacity: 0.5,
												dotsPadding: 10,
												dotsRadius: 50,
												showProgressDots: true,
											}}
											/* slots: 각 슬라이드에 들어가는 내용 (여기서는 Image 컴포넌트들) */
											slots={[
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/EknLajuaH1m0f5qwmTShHz1kqWE.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/EknLajuaH1m0f5qwmTShHz1kqWE.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/EknLajuaH1m0f5qwmTShHz1kqWE.png?width=1024&height=1024 1024w",
													}}
													className={"framer-1x1ajzz"}
													data-framer-name={
														"Gemini Generated_Image_mpcdaimpcdaimpcd (1)"
													}
													layoutDependency={layoutDependency}
													layoutId={"n3POSELKq"}
												/>,
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/N5aKOFJYavXjI7LYHIbcyYBpAKo.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/N5aKOFJYavXjI7LYHIbcyYBpAKo.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/N5aKOFJYavXjI7LYHIbcyYBpAKo.png?width=1024&height=1024 1024w",
													}}
													className={"framer-1lg99t2"}
													data-framer-name={
														"Gemini Generated_Image_b2wh2rb2wh2rb2wh"
													}
													layoutDependency={layoutDependency}
													layoutId={"vdhxDgb80"}
												/>,
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/2035KtTb7E7naUkxxrhkcC3NGM.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/2035KtTb7E7naUkxxrhkcC3NGM.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/2035KtTb7E7naUkxxrhkcC3NGM.png?width=1024&height=1024 1024w",
													}}
													className={"framer-1b2oc79"}
													data-framer-name={
														"Gemini Generated_Image_4v41s64v41s64v41"
													}
													layoutDependency={layoutDependency}
													layoutId={"F6ZSFhhqL"}
												/>,
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/iPthP1XMQQL0MJl2DslKyKKRtA.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/iPthP1XMQQL0MJl2DslKyKKRtA.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/iPthP1XMQQL0MJl2DslKyKKRtA.png?width=1024&height=1024 1024w",
													}}
													className={"framer-19z9tq2"}
													data-framer-name={
														"Gemini Generated_Image_4q8mg34q8mg34q8m"
													}
													layoutDependency={layoutDependency}
													layoutId={"FgQapLORd"}
												/>,
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/fiZdvwGteyrgBTkKLw3MmiIJkk.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/fiZdvwGteyrgBTkKLw3MmiIJkk.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/fiZdvwGteyrgBTkKLw3MmiIJkk.png?width=1024&height=1024 1024w",
													}}
													className={"framer-4xodzv"}
													data-framer-name={
														"Gemini Generated_Image_92mp0992mp0992mp"
													}
													layoutDependency={layoutDependency}
													layoutId={"sTmV6_7T6"}
												/>,
												<Image
													background={{
														alt: "",
														fit: "fill",
														intrinsicHeight: 1024,
														intrinsicWidth: 1024,
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "1024px",
														src: "https://framerusercontent.com/images/PaaRzmhUrDaZnQOPvwfrhQ9iLU.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/PaaRzmhUrDaZnQOPvwfrhQ9iLU.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/PaaRzmhUrDaZnQOPvwfrhQ9iLU.png?width=1024&height=1024 1024w",
													}}
													className={"framer-1mwckda"}
													data-framer-name={
														"Gemini Generated_Image_x4ba3fx4ba3fx4ba"
													}
													layoutDependency={layoutDependency}
													layoutId={"N8yELuci1"}
												/>,
											]}
											startFrom={0}
											style={{
												height: "100%",
												width: "100%",
											}}
											transitionControl={{
												duration: 0,
												type: "tween",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>

							{/* Features 영역: 세 개의 카드(이미지 + 텍스트)로 구성 */}
							<motion.div
								className={"framer-y4v7xm"}
								data-framer-name={"Features"}
								layoutDependency={layoutDependency}
								layoutId={"L3l4aPlD0"}
								style={{
									backgroundColor: "rgb(255, 255, 255)",
								}}
							>
								<motion.div
									className={"framer-v20aur"}
									layoutDependency={layoutDependency}
									layoutId={"x8bHIROpc"}
								>
									{/* 카드 1 */}
									<motion.div
										className={"framer-1x3z1r1"}
										layoutDependency={layoutDependency}
										layoutId={"PUUmyeYHx"}
									>
										<Link
											href={{
												webPageId: "nRqsPdyTa",
											}}
											motionChild={true}
											nodeId={"tNbZPJmMx"}
											openInNewTab={false}
											scopeId={"LduaWW2WS"}
										>
											{/* Image as 링크(a) - lazy 로딩 위치 계산에 componentViewport 사용 */}
											<Image
												as={"a"}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 800,
													intrinsicWidth: 800,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(componentViewport?.height || 1752) -
															1447.5 +
															80 +
															745 +
															80 +
															0 +
															0 +
															0,
													),
													pixelHeight: 500,
													pixelWidth: 629,
													sizes: `max((min(960px, (${componentViewport?.width || "100vw"} - 40px) * 0.935) - 40px) / 3, 1px)`,
													src: "https://framerusercontent.com/images/QwGi7bmeFh0VI8IGqjor202mens.jpeg?width=629&height=500",
													srcSet:
														"https://framerusercontent.com/images/QwGi7bmeFh0VI8IGqjor202mens.jpeg?scale-down-to=512&width=629&height=500 512w,https://framerusercontent.com/images/QwGi7bmeFh0VI8IGqjor202mens.jpeg?width=629&height=500 629w",
												}}
												className={"framer-1trp0d framer-1ythv6z"}
												data-border={true}
												data-framer-name={"Placeholder"}
												layoutDependency={layoutDependency}
												layoutId={"tNbZPJmMx"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgb(34, 34, 34)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
													boxShadow:
														"0px 1px 2px 0px rgba(0, 0, 0, 0.25), 0px 2px 4px 0px rgba(0, 0, 0, 0.25)",
												}}
											/>
										</Link>

										{/* 카드 텍스트: 제목 + 설명 */}
										<motion.div
											className={"framer-1fjkjwt"}
											layoutDependency={layoutDependency}
											layoutId={"H4hg6XwNh"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-5cvpko"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"iMw45qkqI"}
												style={{
													"--extracted-zfisys":
														'"opsz" 32, "wght" 650',
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOalV3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"24px",
															"--framer-font-variation-axes":
																'var(--extracted-zfisys, "opsz" 32, "wght" 650)',
															"--framer-letter-spacing":
																"-0.02em",
															"--framer-line-height":
																"1em",
															"--framer-text-alignment":
																"left",
														}}
													>
														{
															"\uAC15\uC6D0\uD2B9\uBCC4\uC790\uCE58\uB3C4 \uC18D\uCD08"
														}
														{/* 제목: '강원특수자치도 속초' */}
													</motion.h3>
												</React.Fragment>
											</RichText>

											<RichText
												__fromCanvasComponent={true}
												className={"framer-9m3qc"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"dmxT9mHI3"}
												style={{
													"--extracted-2gg91v":
														'"opsz" 32, "wght" 500',
													"--extracted-r6o4lv":
														"rgb(153, 153, 153)",
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"22px",
															"--framer-font-variation-axes":
																'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
															"--framer-letter-spacing":
																"-0.01em",
															"--framer-text-alignment":
																"left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(153, 153, 153))",
														}}
													>
														{
															"\uC124\uC545\uC0B0\uC758 \uC6C5\uC7A5\uD568\uACFC \uB3D9\uD574\uC758 \uD478\uB978 \uBB3C\uACB0, \uADF8\uB9AC\uACE0 \uC2E4\uD5A5\uBBFC \uBB38\uD654\uAC00 \uACF5\uC874\uD558\uB294 \uD65C\uAE30\uCC2C \uBB38\uD654 \uAD00\uAD11 \uB3C4\uC2DC"
														}
														{/* 설명 텍스트 (UTF-16 이스케이프 문자열) */}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>

									{/* 카드 2 (구조 동일) */}
									<motion.div
										className={"framer-x8jf57"}
										layoutDependency={layoutDependency}
										layoutId={"hcAbfJc1w"}
									>
										<Link
											href={{
												webPageId: "UEd5CjrtD",
											}}
											motionChild={true}
											nodeId={"lQYIzno0f"}
											openInNewTab={false}
											scopeId={"LduaWW2WS"}
										>
											<Image
												as={"a"}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 800,
													intrinsicWidth: 800,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(componentViewport?.height || 1752) -
															1447.5 +
															80 +
															745 +
															80 +
															0 +
															0 +
															0,
													),
													pixelHeight: 512,
													pixelWidth: 682,
													sizes: `max((min(960px, (${componentViewport?.width || "100vw"} - 40px) * 0.935) - 40px) / 3, 1px)`,
													src: "https://framerusercontent.com/images/uzQltL2oNOLaiG0xSyjMOg7ixw.jpeg?width=682&height=512",
													srcSet:
														"https://framerusercontent.com/images/uzQltL2oNOLaiG0xSyjMOg7ixw.jpeg?scale-down-to=512&width=682&height=512 512w,https://framerusercontent.com/images/uzQltL2oNOLaiG0xSyjMOg7ixw.jpeg?width=682&height=512 682w",
												}}
												className={"framer-1c095kn framer-1ythv6z"}
												data-framer-name={"Placeholder"}
												layoutDependency={layoutDependency}
												layoutId={"lQYIzno0f"}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
											/>
										</Link>
										<motion.div
											className={"framer-mdj07m"}
											layoutDependency={layoutDependency}
											layoutId={"s2mSWDl3B"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1dlu6dv"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"q3PglOf2r"}
												style={{
													"--extracted-zfisys":
														'"opsz" 32, "wght" 650',
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOalV3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"24px",
															"--framer-font-variation-axes":
																'var(--extracted-zfisys, "opsz" 32, "wght" 650)',
															"--framer-letter-spacing":
																"-0.02em",
															"--framer-line-height":
																"1em",
															"--framer-text-alignment":
																"left",
														}}
													>
														{
															"\uC804\uBD81\uD2B9\uBCC4\uC790\uCE58\uB3C4 \uBB34\uC8FC"
														}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1yjouzn"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"fmZyHCYvD"}
												style={{
													"--extracted-2gg91v":
														'"opsz" 32, "wght" 500',
													"--extracted-r6o4lv":
														"rgb(153, 153, 153)",
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"22px",
															"--framer-font-variation-axes":
																'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
															"--framer-letter-spacing":
																"-0.01em",
															"--framer-text-alignment":
																"left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(153, 153, 153))",
														}}
													>
														{
															"\uBC18\uB527\uBD88\uC774\uAC00 \uC228 \uC26C\uB294 \uCCAD\uC815 \uC790\uC5F0\uD2B9\uBCC4\uC2DC\uC774\uC790, \uB355\uC720\uC0B0\uC758 \uC0AC\uACC4\uB97C \uD488\uC740 \uD0DC\uAD8C\uB3C4\uC758 \uC131\uC9C0."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>

									{/* 카드 3 (구조 동일) */}
									<motion.div
										className={"framer-gy2smq"}
										layoutDependency={layoutDependency}
										layoutId={"F8jc18cvD"}
									>
										<Link
											href={{
												webPageId: "KqxquXeJk",
											}}
											motionChild={true}
											nodeId={"QS1J4epNq"}
											openInNewTab={false}
											scopeId={"LduaWW2WS"}
										>
											<Image
												as={"a"}
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 800,
													intrinsicWidth: 800,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(componentViewport?.height || 1752) -
															1447.5 +
															80 +
															745 +
															80 +
															0 +
															0 +
															0,
													),
													pixelHeight: 720,
													pixelWidth: 1280,
													sizes: `max((min(960px, (${componentViewport?.width || "100vw"} - 40px) * 0.935) - 40px) / 3, 1px)`,
													src: "https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?width=1280&height=720",
													srcSet:
														"https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?scale-down-to=512&width=1280&height=720 512w,https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?scale-down-to=1024&width=1280&height=720 1024w,https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?width=1280&height=720 1280w",
												}}
												className={"framer-1hnbkxx framer-1ythv6z"}
												data-framer-name={"Placeholder"}
												layoutDependency={layoutDependency}
												layoutId={"QS1J4epNq"}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
											/>
										</Link>
										<motion.div
											className={"framer-svj2v6"}
											layoutDependency={layoutDependency}
											layoutId={"q3hMNZpoT"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1wqlz69"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"s2KTaNW0T"}
												style={{
													"--extracted-zfisys":
														'"opsz" 32, "wght" 650',
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h3
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOalV3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"24px",
															"--framer-font-variation-axes":
																'var(--extracted-zfisys, "opsz" 32, "wght" 650)',
															"--framer-letter-spacing":
																"-0.02em",
															"--framer-line-height":
																"1em",
															"--framer-text-alignment":
																"left",
														}}
													>
														{"\uCDA9\uCCAD\uBD81\uB3C4 \uCCAD\uC8FC\uC2DC"}
													</motion.h3>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-3b3mty"}
												fonts={["Inter-Variable"]}
												layoutDependency={layoutDependency}
												layoutId={"WxJGM2AVB"}
												style={{
													"--extracted-2gg91v":
														'"opsz" 32, "wght" 500',
													"--extracted-r6o4lv":
														"rgb(153, 153, 153)",
													"--framer-link-text-color":
														"rgb(0, 153, 255)",
													"--framer-link-text-decoration":
														"underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector":
																"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
															"--framer-font-family":
																'"Inter Variable", "Inter Variable Placeholder", sans-serif',
															"--framer-font-open-type-features":
																"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
															"--framer-font-size":
																"22px",
															"--framer-font-variation-axes":
																'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
															"--framer-letter-spacing":
																"-0.01em",
															"--framer-text-alignment":
																"left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(153, 153, 153))",
														}}
													>
														{
															"\uACC4 \uCD5C\uACE0(\u6700\u53E4)\uC758 \uAE08\uC18D\uD65C\uC790\uBCF8 \uC9C1\uC9C0\uC758 \uC5BC\uC774 \uC0B4\uC544 \uC228 \uC26C\uB294 \uC0DD\uBA85\uACFC \uCC3D\uC870\uC758 \uC5ED\uC0AC \uAD50\uC721 \uBB38\uD654 \uB3C4\uC2DC."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});

/* ---------- CSS scoping 및 export 처리 ---------- */
/* 원본 CSS 배열을 그대로 유지 (Unframer가 생성한 스타일) */
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4AkQ8.framer-1ythv6z, .framer-4AkQ8 .framer-1ythv6z { display: block; }",
	".framer-4AkQ8.framer-1abb9m3 { height: 1752px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-4AkQ8 .framer-13jqi1c-container { flex: none; height: 67px; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-4AkQ8 .framer-b6o5kk { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; left: 0px; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; right: 0px; }",
	".framer-4AkQ8 .framer-1tos9uf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4AkQ8 .framer-l0nmj9, .framer-4AkQ8 .framer-5cvpko, .framer-4AkQ8 .framer-1dlu6dv, .framer-4AkQ8 .framer-1wqlz69 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-4AkQ8 .framer-1rheogc { align-content: center; align-items: center; aspect-ratio: 1.6 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 725px); justify-content: center; max-width: 100%; overflow: visible; padding: 0px; position: relative; width: 721px; }",
	".framer-4AkQ8 .framer-4f17g5-container { flex: none; height: 764px; position: relative; width: 841px; }",
	".framer-4AkQ8 .framer-1x1ajzz, .framer-4AkQ8 .framer-1lg99t2, .framer-4AkQ8 .framer-1b2oc79, .framer-4AkQ8 .framer-19z9tq2, .framer-4AkQ8 .framer-4xodzv, .framer-4AkQ8 .framer-1mwckda { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 1024px); overflow: visible; position: relative; width: 1024px; }",
	".framer-4AkQ8 .framer-y4v7xm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 80px 20px 80px 20px; position: relative; width: 94%; }",
	".framer-4AkQ8 .framer-v20aur { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 100%; overflow: visible; padding: 0px; position: relative; width: 960px; }",
	".framer-4AkQ8 .framer-1x3z1r1, .framer-4AkQ8 .framer-x8jf57, .framer-4AkQ8 .framer-gy2smq { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-4AkQ8 .framer-1trp0d, .framer-4AkQ8 .framer-1c095kn, .framer-4AkQ8 .framer-1hnbkxx { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 307px); justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-4AkQ8 .framer-1fjkjwt, .framer-4AkQ8 .framer-mdj07m, .framer-4AkQ8 .framer-svj2v6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4AkQ8 .framer-9m3qc, .framer-4AkQ8 .framer-1yjouzn, .framer-4AkQ8 .framer-3b3mty { --framer-text-wrap: balance; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	'.framer-4AkQ8[data-border="true"]::after, .framer-4AkQ8 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerLduaWW2WS = withCSS(Component, css, "framer-4AkQ8");
var stdin_default2 = FramerLduaWW2WS;
FramerLduaWW2WS.displayName = "info";
FramerLduaWW2WS.defaultProps = {
	height: 1752,
	width: 1200,
};

/* ---------- 폰트 추가 (Unframer 런타임에 폰트 메타데이터 등록) ---------- */
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerLduaWW2WS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:info
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};

/**
 * ComponentWithRoot: ContextProviders로 라우트/사이트ID/로케일을 감싸서
 * 최종적으로 Framer 생성 컴포넌트를 렌더링하는 래퍼
 *
 * - Props: locale 및 기타 전달 props를 받아 ContextProviders를 통해 하위 컴포넌트에 주입
 */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}

/**
 * ComponentWithRoot.Responsive:
 * - 반응형 브레이크포인트를 지원하는 래퍼 컴포넌트
 * - WithFramerBreakpoints를 사용해 breakpoint별 variant를 제어
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};

/* ComponentWithRoot에 원본 컴포넌트의 정적 속성(예: displayName, defaultProps 등)을 병합 */
Object.assign(ComponentWithRoot, stdin_default2);
var info_default = ComponentWithRoot;
export { info_default as default };