// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";


// Locale: 로케일(언어 코드)을 string으로 표현하는 타입
/**
 * @typedef Locale
 * string
 */


// Props: 이 컴포넌트가 받을 수 있는 속성들(JSDoc용 타입 정의)
/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props


 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";       // Cal.com 예약 위젯 코드 컴포넌트
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";   // Google Maps 위치 표시 컴포넌트
import { Slideshow } from "./chunks/chunk-FET5STFD.js";    // 이미지 슬라이드쇼 컴포넌트
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";// 상단 네비게이션/헤더 컴포넌트
import { routes } from "./chunks/chunk-RX5K52XN.js";       // 라우트/페이지 정보


// virtual:mu-juck
// Unframer가 내부 컨텍스트를 구성할 때 사용하는 가상 모듈 구분용 주석
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";


// /:https://framerusercontent.com/modules/tUwF1Vzr9fHdh6T3oZ5K/V06v9IejFJGHFIYutGRO/wAGXZvecT.js
// 위 URL의 번들 모듈이 이 로컬 코드로 변환된 것
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
    addFonts,                      // 하위 코드 컴포넌트들의 폰트 메타데이터를 수집
    ComponentViewportProvider,     // 이 컴포넌트 기준 뷰포트 정보 컨텍스트 제공
    cx,                            // className을 조건부로 합치는 유틸
    getFonts,                      // 컴포넌트에서 사용하는 폰트 정보 추출
    Image,                         // Framer용 이미지 컴포넌트
    RichText,                      // 캔버스에서 작성한 리치 텍스트 렌더러
    SmartComponentScopedContainer, // 특정 캔버스 노드를 스코프 단위로 감싸는 컨테이너
    useComponentViewport,          // 현재 컴포넌트 뷰포트 정보 훅
    useLocaleInfo,                 // 로케일(언어) 상태/세터 훅
    useVariantState,               // Framer variant + 제스처 상태 관리 훅
    withCSS,                       // 이 컴포넌트 전용 CSS를 스코프에 주입하는 HOC
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer"; // 레이아웃/애니메이션 그룹
import * as React from "react";
import { useRef } from "react";

// 각 서브 컴포넌트가 사용하는 폰트 정보
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);

// 이 컴포넌트에 대응하는 CSS 스코프 해시
var serializationHash = "framer-9ubcm";

// Framer의 variant 키 → CSS 클래스 이름 매핑
var variantClassNames = {
    OjSZ_rcj3: "framer-v-12j0ykc",
};

// 공통 애니메이션 트랜지션 설정
var transition1 = {
    bounce: 0.2,
    delay: 0,
    duration: 0.4,
    type: "spring",
};

// transformTemplate: 항상 X축 중앙 정렬을 먼저 적용한 뒤 나머지 transform 결합
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;

// Transition: MotionConfigContext를 감싸서 하위 motion 요소들이 동일한 transition 사용
var Transition = ({ value, children }) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ?? config.transition;
    const contextValue = React.useMemo(
        () => ({
            ...config,
            transition,
        }),
        [JSON.stringify(transition)],
    );
    return (
        <MotionConfigContext.Provider value={contextValue}>
            {children}
        </MotionConfigContext.Provider>
    );
};

// Variants: children 묶음 전체에 variants 애니메이션을 적용하기 위한 래퍼
var Variants = motion.create(React.Fragment);

// getProps: height/id/width는 떼어내고 나머지 props만 반환(레이아웃용 값 분리)
var getProps = ({ height, id, width, ...props }) => {
    return {
        ...props,
    };
};

// createLayoutDependency: variants와 props.layoutDependency를 합쳐 레이아웃 key 생성
var createLayoutDependency = (props, variants) => {
    if (props.layoutDependency)
        return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};

// 메인 컴포넌트 정의 (Framer가 이 섹션을 렌더링할 때 사용하는 엔트리)
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
    const fallbackRef = useRef(null);                 // 외부에서 ref 미전달 시 사용할 내부 ref
    const refBinding = ref ?? fallbackRef;
    const defaultLayoutId = React.useId();            // layoutId 없을 때 쓸 기본 ID
    const { activeLocale, setLocale } = useLocaleInfo(); // 현재 로케일 정보/변경 함수
    const componentViewport = useComponentViewport();    // 이 컴포넌트 기준 뷰포트 정보
    const { style, className, layoutId, variant, ...restProps } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants,
    } = useVariantState({
        defaultVariant: "OjSZ_rcj3",      // 기본 variant 키
        ref: refBinding,                  // 제스처 감지용 ref
        variant,
        variantClassNames,
    });
    const layoutDependency = createLayoutDependency(props, variants); // 레이아웃 애니메이션 key
    const sharedStyleClassNames = [];                                 // 공통 스타일 클래스(현재 없음)
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames); // 이 컴포넌트 스코프 클래스
    return (
        <LayoutGroup id={layoutId ?? defaultLayoutId}>
            <Variants animate={variants} initial={false}>
                <Transition value={transition1}>
                    <motion.div
                        {...restProps}
                        {...gestureHandlers}
                        className={cx(
                            scopingClassNames,
                            "framer-12j0ykc",
                            className,
                            classNames,
                        )}
                        data-framer-name={"Variant 1"}
                        layoutDependency={layoutDependency}
                        layoutId={"OjSZ_rcj3"}
                        ref={refBinding}
                        style={{
                            ...style,
                        }}
                    >
                        {/* 상단 네비게이션/헤더 영역 – 캔버스 노드 NhpKZWl23을 여기로 스코프 렌더링 */}
                        <ComponentViewportProvider
                            height={64}
                            width={componentViewport?.width || "100vw"}
                            y={(componentViewport?.y || 0) + 0}
                        >
                            <SmartComponentScopedContainer
                                className={"framer-1dr9kea-container"}
                                layoutDependency={layoutDependency}
                                layoutId={"NhpKZWl23-container"}
                                nodeId={"NhpKZWl23"}
                                rendersWithMotion={true}
                                scopeId={"wAGXZvecT"}
                                transformTemplate={transformTemplate1}
                            >
                                {_jsx(stdin_default, {
                                    height: "100%",
                                    id: "NhpKZWl23",
                                    layoutId: "NhpKZWl23",
                                    style: {
                                        width: "100%",
                                    },
                                    width: "100%",
                                })}
                            </SmartComponentScopedContainer>
                        </ComponentViewportProvider>
                        {/* 메인 Features 섹션: 텍스트 설명 + 이미지 카드 레이아웃 */}
                        <motion.div
                            className={"framer-1xswoxm"}
                            data-framer-name={"Features"}
                            layoutDependency={layoutDependency}
                            layoutId={"GgN7TRLTy"}
                            style={{
                                backgroundColor: "rgb(255, 255, 255)",
                            }}
                            transformTemplate={transformTemplate1}
                        >
                            <motion.div
                                className={"framer-15qd4dh"}
                                layoutDependency={layoutDependency}
                                layoutId={"m6EFHcGJl"}
                            >
                                {/* 왼쪽 텍스트 영역: 제목 + 설명 */}
                                <motion.div
                                    className={"framer-1b1twvo"}
                                    layoutDependency={layoutDependency}
                                    layoutId={"pztBQ2K51"}
                                >
                                    {/* 제목 RichText: 적상산(전망대) */}
                                    <RichText
                                        __fromCanvasComponent={true}
                                        className={"framer-1sq6s4i"}
                                        fonts={["Inter-Variable"]}
                                        layoutDependency={layoutDependency}
                                        layoutId={"GcJ5AssVY"}
                                        style={{
                                            "--extracted-2gg91v": '"opsz" 32, "wght" 700',
                                            "--framer-link-text-color": "rgb(0, 153, 255)",
                                            "--framer-link-text-decoration": "underline",
                                        }}
                                        verticalAlignment={"top"}
                                        withExternalLayout={true}
                                    >
                                        <React.Fragment>
                                            <motion.p
                                                style={{
                                                    "--font-selector":
                                                        "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
                                                    "--framer-font-family":
                                                        '"Inter Variable", "Inter Variable Placeholder", sans-serif',
                                                    "--framer-font-open-type-features":
                                                        "'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
                                                    "--framer-font-size": "32px",
                                                    "--framer-font-variation-axes":
                                                        'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
                                                    "--framer-letter-spacing": "-0.03em",
                                                    "--framer-line-height": "1em",
                                                    "--framer-text-alignment": "left",
                                                }}
                                            >
                                                {"\uC801\uC0C1\uC0B0(\uC804\uB9DD\uB300)"}
                                            </motion.p>
                                        </React.Fragment>
                                    </RichText>
                                    {/* 본문 RichText: 적상산·적상전망대 소개 문단 */}
                                    <RichText
                                        __fromCanvasComponent={true}
                                        className={"framer-1w8zuwk"}
                                        fonts={["Inter-Variable"]}
                                        layoutDependency={layoutDependency}
                                        layoutId={"VT4SsOyoD"}
                                        style={{
                                            "--extracted-2gg91v": '"opsz" 32, "wght" 500',
                                            "--extracted-r6o4lv": "rgb(153, 153, 153)",
                                            "--framer-link-text-color": "rgb(0, 153, 255)",
                                            "--framer-link-text-decoration": "underline",
                                        }}
                                        verticalAlignment={"top"}
                                        withExternalLayout={true}
                                    >
                                        <React.Fragment>
                                            <motion.p
                                                style={{
                                                    "--font-selector":
                                                        "SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
                                                    "--framer-font-family":
                                                        '"Inter Variable", "Inter Variable Placeholder", sans-serif',
                                                    "--framer-font-open-type-features":
                                                        "'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
                                                    "--framer-font-size": "24px",
                                                    "--framer-font-variation-axes":
                                                        'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
                                                    "--framer-letter-spacing": "-0.01em",
                                                    "--framer-text-alignment": "left",
                                                    "--framer-text-color":
                                                        "var(--extracted-r6o4lv, rgb(153, 153, 153))",
                                                }}
                                            >
                                                {
                                                    "\uC801\uC0C1\uC0B0\uC740 \uC0AC\uBC29\uC774 \uAE4E\uC544\uC9C0\uB978 \uB4EF\uD55C \uC554\uBCBD\uC73C\uB85C \uC774\uB8E8\uC5B4\uC838 \uC788\uC73C\uBA70, \uADF8 \uC808\uBCBD \uC8FC\uBCC0\uC5D0 \uC720\uB09C\uD788\uB3C4 \uBE68\uAC04 \uB2E8\uD48D\uB098\uBB34\uAC00 \uB9CE\uC544\uC11C \uAC00\uC744\uCCA0\uC774\uBA74 \uB9C8\uCE58 \uC628 \uC0B0\uC774 \uBE68\uAC04 \uCE58\uB9C8\uB97C \uC785\uC740 \uB4EF\uD558\uB2E4\uACE0 \uD558\uC5EC \uC801\uC0C1\uC0B0\uC774\uB77C\uB294 \uC774\uB984\uC774 \uC9C0\uC5B4\uC84C\uC2B5\uB2C8\uB2E4. \uAC70\uB300\uD55C \uAD74\uB69D\uCC98\uB7FC \uC0DD\uAE34 \uC801\uC0C1\uC804\uB9DD\uB300\uB294 \uBB34\uC8FC \uC591\uC218\uBC1C\uC804\uC18C\uC758 \uBC1C\uC804\uC124\uBE44\uC778 \uC870\uC555\uC218\uC870\uB85C \uAC74\uBB3C 3~4\uCE35 \uB192\uC774 \uAF2D\uB300\uAE30\uC5D0 \uC624\uB974\uBA74 \uC18C\uBC31\uC0B0\uB9E5\uACFC \uB355\uC720\uC0B0 \uC804\uACBD\uC774 \uD30C\uB178\uB77C\uB9C8\uCC98\uB7FC \uD3BC\uCCD0\uC838 \uBB34\uC8FC\uC758 \uC544\uB984\uB2E4\uC6B4 \uC0B0\uD558\uB97C \uAC10\uC0C1\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4."
                                                }
                                            </motion.p>
                                        </React.Fragment>
                                    </RichText>
                                </motion.div>
                                {/* 오른쪽 카드: 흰색 배경 박스 안에 슬라이드쇼 배치 */}
                                <motion.div
                                    className={"framer-1bvtlo3"}
                                    data-framer-name={"Placeholder"}
                                    layoutDependency={layoutDependency}
                                    layoutId={"NcCJbJrWX"}
                                    style={{
                                        backgroundColor: "rgb(255, 255, 255)",
                                        borderBottomLeftRadius: 20,
                                        borderBottomRightRadius: 20,
                                        borderTopLeftRadius: 20,
                                        borderTopRightRadius: 20,
                                    }}
                                >
                                    <ComponentViewportProvider>
                                        <SmartComponentScopedContainer
                                            className={"framer-14zxxnu-container"}
                                            isAuthoredByUser={true}  // 사용자가 작성한 외부 모듈
                                            isModuleExternal={true}
                                            layoutDependency={layoutDependency}
                                            layoutId={"fyAsh4rVn-container"}
                                            nodeId={"fyAsh4rVn"}
                                            rendersWithMotion={true}
                                            scopeId={"wAGXZvecT"}
                                        >
                                            {/* Slideshow: 적상산 관련 이미지를 자동 재생/도트/화살표로 보여줌 */}
                                            <Slideshow
                                                alignment={"center"}
                                                arrowOptions={{
                                                    arrowFill: "rgba(0, 0, 0, 0.2)",
                                                    arrowGap: 10,
                                                    arrowPadding: 20,
                                                    arrowPaddingBottom: 0,
                                                    arrowPaddingLeft: 0,
                                                    arrowPaddingRight: 0,
                                                    arrowPaddingTop: 0,
                                                    arrowPosition: "auto",
                                                    arrowRadius: 40,
                                                    arrowShouldFadeIn: false,
                                                    arrowShouldSpace: true,
                                                    arrowSize: 40,
                                                    showMouseControls: true,
                                                }}
                                                autoPlayControl={true}
                                                borderRadius={0}
                                                direction={"left"}
                                                dragControl={false}
                                                effectsOptions={{
                                                    effectsHover: true,
                                                    effectsOpacity: 1,
                                                    effectsPerspective: 1200,
                                                    effectsRotate: 0,
                                                    effectsScale: 1,
                                                    playOffscreen: false,
                                                }}
                                                fadeOptions={{
                                                    fadeAlpha: 0,
                                                    fadeContent: false,
                                                    fadeInset: 0,
                                                    fadeWidth: 25,
                                                    overflow: false,
                                                }}
                                                gap={10}
                                                height={"100%"}
                                                id={"fyAsh4rVn"}
                                                intervalControl={2.5}
                                                itemAmount={1}
                                                layoutId={"fyAsh4rVn"}
                                                padding={0}
                                                paddingBottom={0}
                                                paddingLeft={0}
                                                paddingPerSide={false}
                                                paddingRight={0}
                                                paddingTop={0}
                                                progressOptions={{
                                                    dotsActiveOpacity: 1,
                                                    dotsBackground: "rgba(0, 0, 0, 0.2)",
                                                    dotsBlur: 0,
                                                    dotsFill: "rgb(255, 255, 255)",
                                                    dotsGap: 10,
                                                    dotsInset: 10,
                                                    dotSize: 10,
                                                    dotsOpacity: 0.5,
                                                    dotsPadding: 10,
                                                    dotsRadius: 50,
                                                    showProgressDots: true,
                                                }}
                                                slots={[
                                                    <Image
                                                        background={{
                                                            alt: "",
                                                            fit: "fill",
                                                            pixelHeight: 431,
                                                            pixelWidth: 713,
                                                            sizes: "400px",
                                                            src: "https://framerusercontent.com/images/wdYPbY3XUZHxDaE8TloxbtwP8U.jpg?width=713&height=431",
                                                            srcSet:
                                                                "https://framerusercontent.com/images/wdYPbY3XUZHxDaE8TloxbtwP8U.jpg?scale-down-to=512&width=713&height=431 512w,[https://framerusercontent.com/images/wdYPbY3XUZHxDaE8TloxbtwP8U.jpg?width=713&height=431](https://framerusercontent.com/images/wdYPbY3XUZHxDaE8TloxbtwP8U.jpg?width=713&height=431) 713w",
                                                        }}
                                                        className={"framer-1m635fv"}
                                                        layoutDependency={layoutDependency}
                                                        layoutId={"kdY5rhbBI"}
                                                    />,
                                                    <Image
                                                        background={{
                                                            alt: "",
                                                            fit: "fill",
                                                            pixelHeight: 571,
                                                            pixelWidth: 986,
                                                            sizes: "400px",
                                                            src: "https://framerusercontent.com/images/mulEaY5vgttt7010MEBYh4uy34.jpg?width=986&height=571",
                                                            srcSet:
                                                                "https://framerusercontent.com/images/mulEaY5vgttt7010MEBYh4uy34.jpg?scale-down-to=512&width=986&height=571 512w,[https://framerusercontent.com/images/mulEaY5vgttt7010MEBYh4uy34.jpg?width=986&height=571](https://framerusercontent.com/images/mulEaY5vgttt7010MEBYh4uy34.jpg?width=986&height=571) 986w",
                                                        }}
                                                        className={"framer-1da9sit"}
                                                        layoutDependency={layoutDependency}
                                                        layoutId={"TXvYcsshQ"}
                                                    />,
                                                    <Image
                                                        background={{
                                                            alt: "",
                                                            fit: "fill",
                                                            pixelHeight: 597,
                                                            pixelWidth: 887,
                                                            sizes: "400px",
                                                            src: "https://framerusercontent.com/images/cVeq11YfzLPC9DjdoUlEbB5P0.jpg?width=887&height=597",
                                                            srcSet:
                                                                "https://framerusercontent.com/images/cVeq11YfzLPC9DjdoUlEbB5P0.jpg?scale-down-to=512&width=887&height=597 512w,[https://framerusercontent.com/images/cVeq11YfzLPC9DjdoUlEbB5P0.jpg?width=887&height=597](https://framerusercontent.com/images/cVeq11YfzLPC9DjdoUlEbB5P0.jpg?width=887&height=597) 887w",
                                                        }}
                                                        className={"framer-1fyn7lb"}
                                                        layoutDependency={layoutDependency}
                                                        layoutId={"AxzghmYyd"}
                                                    />,
                                                    <Image
                                                        background={{
                                                            alt: "",
                                                            fit: "fill",
                                                            pixelHeight: 602,
                                                            pixelWidth: 891,
                                                            sizes: "400px",
                                                            src: "https://framerusercontent.com/images/RSydhj9o5P9I8IFlzHAm7PJpFME.jpg?width=891&height=602",
                                                            srcSet:
                                                                "https://framerusercontent.com/images/RSydhj9o5P9I8IFlzHAm7PJpFME.jpg?scale-down-to=512&width=891&height=602 512w,[https://framerusercontent.com/images/RSydhj9o5P9I8IFlzHAm7PJpFME.jpg?width=891&height=602](https://framerusercontent.com/images/RSydhj9o5P9I8IFlzHAm7PJpFME.jpg?width=891&height=602) 891w",
                                                        }}
                                                        className={"framer-14l94fk"}
                                                        layoutDependency={layoutDependency}
                                                        layoutId={"JvVYKPqHE"}
                                                    />,
                                                    <Image
                                                        background={{
                                                            alt: "",
                                                            fit: "fill",
                                                            pixelHeight: 405,
                                                            pixelWidth: 633,
                                                            sizes: "400px",
                                                            src: "https://framerusercontent.com/images/rJR3JnwQNu4nN346y5HbRWXufQ.jpg?width=633&height=405",
                                                            srcSet:
                                                                "https://framerusercontent.com/images/rJR3JnwQNu4nN346y5HbRWXufQ.jpg?scale-down-to=512&width=633&height=405 512w,[https://framerusercontent.com/images/rJR3JnwQNu4nN346y5HbRWXufQ.jpg?width=633&height=405](https://framerusercontent.com/images/rJR3JnwQNu4nN346y5HbRWXufQ.jpg?width=633&height=405) 633w",
                                                        }}
                                                        className={"framer-ne0cn7"}
                                                        layoutDependency={layoutDependency}
                                                        layoutId={"AZVOECwrm"}
                                                    />,
                                                ]}
                                                startFrom={0}
                                                style={{
                                                    height: "100%",
                                                    width: "100%",
                                                }}
                                                transitionControl={{
                                                    damping: 40,
                                                    delay: 0,
                                                    mass: 1,
                                                    stiffness: 200,
                                                    type: "spring",
                                                }}
                                                width={"100%"}
                                            />
                                        </SmartComponentScopedContainer>
                                    </ComponentViewportProvider>
                                </motion.div>
                            </motion.div>
							<motion.div
								className={"framer-eiwnpu"}
								layoutDependency={layoutDependency}
								layoutId={"AJT9MuFYA"}
							>
								<motion.div
									className={"framer-1wndb7j"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"lWMA5WP2S"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-4fpw18-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"JBku3Y6pH-container"}
											nodeId={"JBku3Y6pH"}
											rendersWithMotion={true}
											scopeId={"wAGXZvecT"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"\uC801\uC0C1\uC0B0"}
												height={"100%"}
												id={"JBku3Y6pH"}
												isMixedBorderRadius={false}
												layoutId={"JBku3Y6pH"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={15}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-h8u3sx"}
									layoutDependency={layoutDependency}
									layoutId={"hkOkGmNtW"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1tr2c2m"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"bDZew5RWt"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8\uC815\uBCF4"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1rpaae5"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"QuyhXlYcm"}
										style={{
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC8FC\uC18C : \uC804\uBD81 \uBB34\uC8FC\uAD70 \uC801\uC0C1\uBA74 \uBD81\uCC3D\uB9AC \uC0B0119-8 "
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{"\uC601\uC5C5 \uC2DC\uAC04 : 09:00 ~ 18:00 "}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												{"\uC804\uD654\uBC88\uD638 : 063-322-4174"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1o8vtwp"}
								layoutDependency={layoutDependency}
								layoutId={"gWwFZ81Ty"}
							>
								<motion.div
									className={"framer-1ckziw9"}
									layoutDependency={layoutDependency}
									layoutId={"LKJYWinnQ"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-nzf985"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"mrxColFXH"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uC608\uC57D \uD558\uAE30"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1wspq7u"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"GViAKM8DY"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1dnh53j"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"vcjRluRAw"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										className={"framer-rbj59s"}
										data-framer-name={"Placeholder"}
										layoutDependency={layoutDependency}
										layoutId={"nr4wSlhrD"}
										style={{
											backgroundColor: "rgb(245, 245, 245)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1wtvtzy-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"fWBkSXks9-container"}
												nodeId={"fWBkSXks9"}
												rendersWithMotion={true}
												scopeId={"wAGXZvecT"}
											>
												<Calcom
													darkTheme={"rgb(250, 250, 250)"}
													eventLink={
														"https://cal.com/framer-placeholder/default"
													}
													height={"100%"}
													id={"fWBkSXks9"}
													layout={"month_view"}
													layoutId={"fWBkSXks9"}
													lightTheme={"rgb(41, 41, 41)"}
													showEventTypeDetails={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													theme={"auto"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-9ubcm.framer-1cjwn8l, .framer-9ubcm .framer-1cjwn8l { display: block; }",
	".framer-9ubcm.framer-12j0ykc { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-9ubcm .framer-1dr9kea-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-9ubcm .framer-1xswoxm { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-9ubcm .framer-15qd4dh, .framer-9ubcm .framer-1o8vtwp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-9ubcm .framer-1b1twvo { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-9ubcm .framer-1sq6s4i, .framer-9ubcm .framer-1tr2c2m, .framer-9ubcm .framer-nzf985 { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-9ubcm .framer-1w8zuwk, .framer-9ubcm .framer-1rpaae5, .framer-9ubcm .framer-1wspq7u { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-9ubcm .framer-1bvtlo3, .framer-9ubcm .framer-1dnh53j, .framer-9ubcm .framer-rbj59s { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-9ubcm .framer-14zxxnu-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-9ubcm .framer-1m635fv, .framer-9ubcm .framer-1da9sit, .framer-9ubcm .framer-1fyn7lb, .framer-9ubcm .framer-14l94fk, .framer-9ubcm .framer-ne0cn7 { height: 300px; position: relative; width: 400px; }",
	".framer-9ubcm .framer-eiwnpu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-9ubcm .framer-1wndb7j { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-9ubcm .framer-4fpw18-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-9ubcm .framer-h8u3sx, .framer-9ubcm .framer-1ckziw9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-9ubcm .framer-1wtvtzy-container { flex: none; height: 480px; position: relative; width: 480px; }",
];
// CSS와 스코프 클래스("framer-9ubcm")를 입힌 최종 Framer 컴포넌트 생성
var FramerwAGXZvecT = withCSS(Component, css, "framer-9ubcm");

// 내부에서 사용할 기본 컴포넌트 별칭
var stdin_default2 = FramerwAGXZvecT;

// React DevTools 등에서 보일 컴포넌트 이름
FramerwAGXZvecT.displayName = "mu_juck";

// 기본 프레임 크기(Framer 캔버스 기준)
FramerwAGXZvecT.defaultProps = {
    height: 1659,
    width: 1200,
};

// Inter Variable 폰트에서 사용할 가변 폰트 축(옵티컬 사이즈/굵기)
var variationAxes = [
    {
        defaultValue: 14,
        maxValue: 32,
        minValue: 14,
        name: "Optical size", // 글자 크기에 따라 최적화되는 축
        tag: "opsz",
    },
    {
        defaultValue: 400,
        maxValue: 900,
        minValue: 100,
        name: "Weight",       // 글자 굵기 축
        tag: "wght",
    },
];

// 이 컴포넌트와 하위 컴포넌트에서 쓰는 모든 폰트를 등록
addFonts(
    FramerwAGXZvecT,
    [
        {
            explicitInter: true,
            fonts: [
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange:
                        "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
                    url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
                    url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange: "U+1F00-1FFF",
                    url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange: "U+0370-03FF",
                    url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange:
                        "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
                    url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange:
                        "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
                    url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
                    variationAxes,
                    weight: "400",
                },
                {
                    cssFamilyName: "Inter Variable",
                    source: "framer",
                    style: "normal",
                    uiFamilyName: "Inter",
                    unicodeRange:
                        "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
                    url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
                    variationAxes,
                    weight: "400",
                },
            ],
        },
        // 상단에서 가져온 각 서브 컴포넌트의 폰트 설정도 함께 등록
        ...Navigation3Fonts,
        ...SlideshowFonts,
        ...GoogleMapsFonts,
        ...CalComFonts,
    ],
    {
        supportsExplicitInterCodegen: true, // Inter 폰트 최적 코드생성 지원 플래그
    },
);


// virtual:mu-juck
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];                  // 사용 중인 로케일 목록(현재는 없음)
var defaultResponsiveVariants = {}; // 브레이크포인트별 기본 variant 매핑

/** @type {function(Props): any} */
// 루트에서 ContextProviders로 감싸 실제 페이지 컴포넌트를 렌더링하는 래퍼
function ComponentWithRoot({ locale, ...rest }) {
    return (
        <ContextProviders
            routes={routes}        // 라우트 정보
            framerSiteId={
                "3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
            }                      // Framer 사이트 ID
            locale={locale}        // 활성 로케일
            locales={locales}      // 지원 로케일 목록
        >
            {jsx(stdin_default2, {
                ...rest,           // 나머지 props를 실제 페이지 컴포넌트에 전달
            })}
        </ContextProviders>
    );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Unframer에서 사용하는 반응형 브레이크포인트 타입
 */


/**
 * @typedef VariantsMap
 * 브레이크포인트 → variant 이름을 매핑한 타입 (반드시 base 키는 있어야 함)
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */


/**
 * 모든 브레이크포인트에 대해 MuJuckFramerComponent를 렌더링하는 헬퍼.
 * props.variants에 브레이크포인트별 variant를 넣어 주면, 각 뷰포트에 맞게 알아서 적용됨.
 */
// 반응형용 헬퍼 컴포넌트 (브레이크포인트별로 다른 variant를 사용)
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
    return (
        <ContextProviders
            routes={routes}
            framerSiteId={
                "3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
            }
            locale={locale}
            locales={locales}
        >
            <WithFramerBreakpoints
                Component={stdin_default2}       // 실제 페이지 컴포넌트
                variants={defaultResponsiveVariants}
                {...rest}
            />
        </ContextProviders>
    );
};

// 원래 컴포넌트에 있던 static 속성들을 래퍼에도 복사
Object.assign(ComponentWithRoot, stdin_default2);

// 최종 export용 별칭 설정
var mu_juck_default = ComponentWithRoot;
export { mu_juck_default as default };          // 이 파일의 기본 내보내기
