// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";
import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:cheong-tree
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/W614KxvCn2J5r2JE0WmK/vGNrSQUNwCG0wHjGWenJ/cithDcufQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);
var serializationHash = "framer-LANU6";
var variantClassNames = {
	AfChvm2MB: "framer-v-1312jpg",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "AfChvm2MB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1312jpg",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"AfChvm2MB"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-6mwcbs-container"}
								layoutDependency={layoutDependency}
								layoutId={"UqIcKfVot-container"}
								nodeId={"UqIcKfVot"}
								rendersWithMotion={true}
								scopeId={"cithDcufQ"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "UqIcKfVot",
									layoutId: "UqIcKfVot",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-19k7xwg"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"aZvFkdHxb"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-1xfjwrr"}
								layoutDependency={layoutDependency}
								layoutId={"Ja1pGWosa"}
							>
								<motion.div
									className={"framer-dsc62r"}
									layoutDependency={layoutDependency}
									layoutId={"KBrSZ_mhD"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1j23n7i"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"kbkC_h_Y2"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"TREE .BRING"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-tsio39"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"mEqT24Emo"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uD2B8\uB9AC\uBE0C\uB9C1 [TREE : \uB098\uBB34, BRING : ~\uAC00\uC838\uC624\uB2E4] \uC790\uC5F0\uACFC \uACE0\uAC1D\uC758 \uB9CC\uC871\uAC10\uC744 \uAC00\uC838\uC624\uB2E4\uB77C\uB294 \uC758\uBBF8\uB97C \uAC00\uC9C4 \uC774\uB984\uC785\uB2C8\uB2E4.  \uB3C4\uC2EC\uC18D\uC5D0\uC11C\uB3C4 \uC990\uAE38 \uC218 \uC788\uB294 \uD790\uB9C1\uC774\uB77C\uB294 \uC8FC\uC81C\uB85C \uC2DD\uBB3C\uC6D0 \uCEE8\uC149\uC758 \uCD08\uB85D\uCD08\uB85D\uD55C \uCCAD\uC8FC \uCE74\uD398 '\uD2B8\uB9AC\uBE0C\uB9C1'  \uB9C8\uCE58 \uC790\uC5F0\uC18D\uC5D0 \uB4E4\uC5B4\uC640 \uC788\uB294 \uAC83\uCC98\uB7FC \uC0AC\uACC4\uC808 \uB0B4\uB0B4 \uD478\uB987\uD478\uB987\uD55C \uC2DD\uBB3C\uB4E4\uC774 \uAC00\uB4DD\uD55C \uC2E4\uB0B4\uC815\uC6D0\uACFC \uC2DC\uC6D0\uD55C \uBB3C\uC18C\uB9AC\uAC00 \uB4E4\uB9AC\uB294 \uC2E4\uB0B4\uC5F0\uBABB\uC774 \uB9E4\uC7A5 \uD55C \uAC00\uC6B4\uB370\uC5D0 \uD06C\uAC8C \uC790\uB9AC\uC7A1\uACE0 \uC788\uC2B5\uB2C8\uB2E4."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-xyyuu5"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"cGLHyHl5P"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1jlfh63-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"ud6_E0w7d-container"}
											nodeId={"ud6_E0w7d"}
											rendersWithMotion={true}
											scopeId={"cithDcufQ"}
										>
											<Slideshow
												alignment={"center"}
												arrowOptions={{
													arrowFill: "rgba(0, 0, 0, 0.2)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: 0,
													arrowPosition: "auto",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: true,
													arrowSize: 40,
													showMouseControls: true,
												}}
												autoPlayControl={true}
												borderRadius={0}
												direction={"left"}
												dragControl={false}
												effectsOptions={{
													effectsHover: true,
													effectsOpacity: 1,
													effectsPerspective: 1200,
													effectsRotate: 0,
													effectsScale: 1,
													playOffscreen: false,
												}}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												id={"ud6_E0w7d"}
												intervalControl={2.5}
												itemAmount={1}
												layoutId={"ud6_E0w7d"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												progressOptions={{
													dotsActiveOpacity: 1,
													dotsBackground: "rgba(0, 0, 0, 0.2)",
													dotsBlur: 0,
													dotsFill: "rgb(255, 255, 255)",
													dotsGap: 10,
													dotsInset: 10,
													dotSize: 10,
													dotsOpacity: 0.5,
													dotsPadding: 10,
													dotsRadius: 50,
													showProgressDots: true,
												}}
												slots={[
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 799.9999880790713,
															intrinsicWidth: 599.9999910593034,
															pixelHeight: 1280,
															pixelWidth: 960,
															sizes: "600px",
															src: "https://framerusercontent.com/images/Xs8fVDljXiACuTblvwiki8v16U.jpeg?width=960&height=1280",
															srcSet:
																"https://framerusercontent.com/images/Xs8fVDljXiACuTblvwiki8v16U.jpeg?scale-down-to=1024&width=960&height=1280 768w,https://framerusercontent.com/images/Xs8fVDljXiACuTblvwiki8v16U.jpeg?width=960&height=1280 960w",
														}}
														className={"framer-1flhm1r"}
														data-framer-name={"\xCD\x8A\xB8\xEB\xA6\xAC1"}
														layoutDependency={layoutDependency}
														layoutId={"UIrRgKYou"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 799.9999880790713,
															intrinsicWidth: 639.999990463257,
															pixelHeight: 1280,
															pixelWidth: 1024,
															sizes: "640px",
															src: "https://framerusercontent.com/images/ZWmKOG8rT9t8WWU7oFx01OrYe6I.jpeg?width=1024&height=1280",
															srcSet:
																"https://framerusercontent.com/images/ZWmKOG8rT9t8WWU7oFx01OrYe6I.jpeg?scale-down-to=1024&width=1024&height=1280 819w,https://framerusercontent.com/images/ZWmKOG8rT9t8WWU7oFx01OrYe6I.jpeg?width=1024&height=1280 1024w",
														}}
														className={"framer-kxcjnl"}
														data-framer-name={"\xCD\x8A\xB8\xEB\xA6\xAC2"}
														layoutDependency={layoutDependency}
														layoutId={"WkfNcdQLa"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 799.9999880790713,
															intrinsicWidth: 639.999990463257,
															pixelHeight: 1280,
															pixelWidth: 1024,
															sizes: "640px",
															src: "https://framerusercontent.com/images/DHvoRkqIobl7AUdbmUYqqfZ9nQU.jpeg?width=1024&height=1280",
															srcSet:
																"https://framerusercontent.com/images/DHvoRkqIobl7AUdbmUYqqfZ9nQU.jpeg?scale-down-to=1024&width=1024&height=1280 819w,https://framerusercontent.com/images/DHvoRkqIobl7AUdbmUYqqfZ9nQU.jpeg?width=1024&height=1280 1024w",
														}}
														className={"framer-1delpy5"}
														data-framer-name={"\xCD\x8A\xB8\xEB\xA6\x904"}
														layoutDependency={layoutDependency}
														layoutId={"UrYbCoaG6"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 799.9999880790713,
															intrinsicWidth: 449.9999932944776,
															pixelHeight: 1280,
															pixelWidth: 720,
															sizes: "450px",
															src: "https://framerusercontent.com/images/hPNYrvdM0w0gPRnKhDoMidWEw.jpeg?width=720&height=1280",
															srcSet:
																"https://framerusercontent.com/images/hPNYrvdM0w0gPRnKhDoMidWEw.jpeg?scale-down-to=1024&width=720&height=1280 576w,https://framerusercontent.com/images/hPNYrvdM0w0gPRnKhDoMidWEw.jpeg?width=720&height=1280 720w",
														}}
														className={"framer-124fiq5"}
														data-framer-name={"\xCD\x8A\xB8\xEB\xA6\xAC3"}
														layoutDependency={layoutDependency}
														layoutId={"Zq9XrsWWp"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 533.1249920558186,
															intrinsicWidth: 799.9999880790713,
															pixelHeight: 853,
															pixelWidth: 1280,
															sizes: "799.8124px",
															src: "https://framerusercontent.com/images/N11IeNOdM9jlloscfjRgI1NJg.jpeg?width=1280&height=853",
															srcSet:
																"https://framerusercontent.com/images/N11IeNOdM9jlloscfjRgI1NJg.jpeg?scale-down-to=512&width=1280&height=853 512w,https://framerusercontent.com/images/N11IeNOdM9jlloscfjRgI1NJg.jpeg?scale-down-to=1024&width=1280&height=853 1024w,https://framerusercontent.com/images/N11IeNOdM9jlloscfjRgI1NJg.jpeg?width=1280&height=853 1280w",
														}}
														className={"framer-1dax1i"}
														data-framer-name={"\xCD\x8A\xB8\xEB\xA6\xAC5"}
														layoutDependency={layoutDependency}
														layoutId={"ZuPq7OyO8"}
													/>,
												]}
												startFrom={0}
												style={{
													height: "100%",
													width: "100%",
												}}
												transitionControl={{
													damping: 40,
													delay: 0,
													mass: 1,
													stiffness: 200,
													type: "spring",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-bzk373"}
								layoutDependency={layoutDependency}
								layoutId={"WHo1hp9C_"}
							>
								<motion.div
									className={"framer-1f6ak7m"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"Qa29I0AAk"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-eule7d-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"LWn2I4OSc-container"}
											nodeId={"LWn2I4OSc"}
											rendersWithMotion={true}
											scopeId={"cithDcufQ"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"tree .bring"}
												height={"100%"}
												id={"LWn2I4OSc"}
												isMixedBorderRadius={false}
												layoutId={"LWn2I4OSc"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={15}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-tr6q2k"}
									layoutDependency={layoutDependency}
									layoutId={"ycJcvppUd"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-copojm"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"biB2N2Y_1"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8 \uC815\uBCF4"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1iugxti"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"ubTiBYepl"}
										style={{
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{"\uC8FC\uC18C : "}
												<motion.strong>
													{
														"\uCDA9\uBD81 \uCCAD\uC8FC\uC2DC \uC11C\uC6D0\uAD6C \uB0A8\uC774\uBA74 \uCCAD\uB0A8\uB85C 1388-36"
													}
												</motion.strong>
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												<motion.strong>
													{"\uC601\uC5C5 \uC2DC\uAC04 : 10:00 - 22:00"}
												</motion.strong>
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												<motion.strong>
													{"\uC804\uD654\uBC88\uD638 : 0507 - 1444 - 7566"}
												</motion.strong>
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1rvcdv"}
								layoutDependency={layoutDependency}
								layoutId={"R_SlyW5Ko"}
							>
								<motion.div
									className={"framer-1qpwhwl"}
									layoutDependency={layoutDependency}
									layoutId={"iLOHm2Rof"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-13knpd5"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"oRSE4dCBP"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uC608\uC57D \uD558\uAE30"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1rbtbrf"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"qz6JhPTVW"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1aqm36l"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"hEyWajQIV"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1g5inl5-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"KYtfovLya-container"}
											nodeId={"KYtfovLya"}
											rendersWithMotion={true}
											scopeId={"cithDcufQ"}
										>
											<Calcom
												darkTheme={"rgb(250, 250, 250)"}
												eventLink={"https://cal.com/framer-placeholder/default"}
												height={"100%"}
												id={"KYtfovLya"}
												layout={"month_view"}
												layoutId={"KYtfovLya"}
												lightTheme={"rgb(41, 41, 41)"}
												showEventTypeDetails={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												theme={"auto"}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-LANU6.framer-1i6bg6b, .framer-LANU6 .framer-1i6bg6b { display: block; }",
	".framer-LANU6.framer-1312jpg { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-LANU6 .framer-6mwcbs-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-LANU6 .framer-19k7xwg { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-LANU6 .framer-1xfjwrr, .framer-LANU6 .framer-1rvcdv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-LANU6 .framer-dsc62r { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-LANU6 .framer-1j23n7i, .framer-LANU6 .framer-copojm, .framer-LANU6 .framer-13knpd5 { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-LANU6 .framer-tsio39, .framer-LANU6 .framer-1iugxti, .framer-LANU6 .framer-1rbtbrf { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-LANU6 .framer-xyyuu5, .framer-LANU6 .framer-1aqm36l { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-LANU6 .framer-1jlfh63-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-LANU6 .framer-1flhm1r { aspect-ratio: 0.7499999999999999 / 1; height: var(--framer-aspect-ratio-supported, 800px); overflow: visible; position: relative; width: 600px; }",
	".framer-LANU6 .framer-kxcjnl, .framer-LANU6 .framer-1delpy5 { aspect-ratio: 0.7999999999999999 / 1; height: var(--framer-aspect-ratio-supported, 800px); overflow: visible; position: relative; width: 640px; }",
	".framer-LANU6 .framer-124fiq5 { aspect-ratio: 0.5625 / 1; height: var(--framer-aspect-ratio-supported, 800px); overflow: visible; position: relative; width: 450px; }",
	".framer-LANU6 .framer-1dax1i { aspect-ratio: 1.5005861664712778 / 1; height: var(--framer-aspect-ratio-supported, 533px); overflow: visible; position: relative; width: 800px; }",
	".framer-LANU6 .framer-bzk373 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-LANU6 .framer-1f6ak7m { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-LANU6 .framer-eule7d-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-LANU6 .framer-tr6q2k, .framer-LANU6 .framer-1qpwhwl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-LANU6 .framer-1g5inl5-container { flex: none; height: 480px; position: relative; width: 480px; }",
];
var FramercithDcufQ = withCSS(Component, css, "framer-LANU6");
var stdin_default2 = FramercithDcufQ;
FramercithDcufQ.displayName = "cheong_tree";
FramercithDcufQ.defaultProps = {
	height: 1659,
	width: 1200,
};
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramercithDcufQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
		...GoogleMapsFonts,
		...CalComFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cheong-tree
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CheongTreeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cheong_tree_default = ComponentWithRoot;
export { cheong_tree_default as default };
