// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";
import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:cheong-choeng
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mQgllfNfup2TScQ0dGo1/pELK60zd9lgFJBJtZtWT/Cpv0tJHMt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);
var serializationHash = "framer-K1iwW";
var variantClassNames = {
	QZIYSZSqN: "framer-v-1aot3ny",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "QZIYSZSqN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1aot3ny",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"QZIYSZSqN"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-3rpjp0-container"}
								layoutDependency={layoutDependency}
								layoutId={"n_9I7HSlG-container"}
								nodeId={"n_9I7HSlG"}
								rendersWithMotion={true}
								scopeId={"Cpv0tJHMt"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "n_9I7HSlG",
									layoutId: "n_9I7HSlG",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-ut7mb1"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"DErxZxLAu"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-1c8h9pd"}
								layoutDependency={layoutDependency}
								layoutId={"XJP566B_X"}
							>
								<motion.div
									className={"framer-1ve4jd0"}
									layoutDependency={layoutDependency}
									layoutId={"nDPvorD05"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-19lsyxr"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"aO4KApXzC"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uCCAD\uB0A8\uB300"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1xyv070"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"UmZRrH3A_"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCDA9\uCCAD\uBD81\uB3C4 \uCCAD\uC6D0\uAD70 \uB300\uCCAD\uB310 \uBD80\uADFC \uC57D 55\uB9CC \uD3C9\uC5D0 \uC9C0\uC740 \uB300\uD1B5\uB839 \uC804\uC6A9 \uBCC4\uC7A5\uC73C\uB85C \uB0A8\uCABD\uC5D0 \uC788\uB294 \uCCAD\uC640\uB300\uB77C\uB294 \uC758\uBBF8\uC774\uB2E4.  \uC81C5\uACF5\uD654\uAD6D \uB54C \uC9C0\uC740 \uAC83\uC73C\uB85C \uB300\uCCAD\uB310 \uC77C\uB300\uC5D0 \uB300\uD55C \uAD6D\uB9BD\uACF5\uC6D0 \uD6FC\uC190 \uB4F1\uC758 \uB9D0\uC37D\uC774 \uC788\uC5B4 1988\uB144 5\uACF5\uBE44\uB9AC\uD2B9\uBCC4\uC704\uC6D0\uD68C\uC5D0\uC11C \uD604\uC9C0\uC870\uC0AC\uB97C \uD558\uAE30\uB3C4 \uD588\uB2E4. \uB300\uD1B5\uB839\uC758 \uBCC4\uC7A5\uC740 \uC774\uC2B9\uB9CC \uB300\uD1B5\uB839 \uC2DC\uC808\uBD80\uD130 \uAE40\uD574\uB97C \uBE44\uB86F\uD574 4\uAD70\uB370\uAC00 \uC788\uC5C8\uB2E4."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-132ydxw"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"vT5x7Jiak"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1y0xmn5-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"jd7jGKtrU-container"}
											nodeId={"jd7jGKtrU"}
											rendersWithMotion={true}
											scopeId={"Cpv0tJHMt"}
										>
											<Slideshow
												alignment={"center"}
												arrowOptions={{
													arrowFill: "rgba(0, 0, 0, 0.2)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: 0,
													arrowPosition: "auto",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: true,
													arrowSize: 40,
													showMouseControls: true,
												}}
												autoPlayControl={true}
												borderRadius={0}
												direction={"left"}
												dragControl={false}
												effectsOptions={{
													effectsHover: true,
													effectsOpacity: 1,
													effectsPerspective: 1200,
													effectsRotate: 0,
													effectsScale: 1,
													playOffscreen: false,
												}}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												id={"jd7jGKtrU"}
												intervalControl={2.5}
												itemAmount={1}
												layoutId={"jd7jGKtrU"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												progressOptions={{
													dotsActiveOpacity: 1,
													dotsBackground: "rgba(0, 0, 0, 0.2)",
													dotsBlur: 0,
													dotsFill: "rgb(255, 255, 255)",
													dotsGap: 10,
													dotsInset: 10,
													dotSize: 10,
													dotsOpacity: 0.5,
													dotsPadding: 10,
													dotsRadius: 50,
													showProgressDots: true,
												}}
												slots={[
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 639.7499809339648,
															intrinsicWidth: 959.9999713897713,
															pixelHeight: 853,
															pixelWidth: 1280,
															sizes: "960.3751px",
															src: "https://framerusercontent.com/images/9xxxOb27xBhmJkbCZ1itkYavccA.jpeg?width=1280&height=853",
															srcSet:
																"https://framerusercontent.com/images/9xxxOb27xBhmJkbCZ1itkYavccA.jpeg?scale-down-to=512&width=1280&height=853 512w,https://framerusercontent.com/images/9xxxOb27xBhmJkbCZ1itkYavccA.jpeg?scale-down-to=1024&width=1280&height=853 1024w,https://framerusercontent.com/images/9xxxOb27xBhmJkbCZ1itkYavccA.jpeg?width=1280&height=853 1280w",
														}}
														className={"framer-1uav7l5"}
														data-framer-name={
															"\xCC\xB2\xAD\xEB\x82\xA8\xEB\x8C\x801"
														}
														layoutDependency={layoutDependency}
														layoutId={"encI3Xgvk"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 539.9999839067464,
															intrinsicWidth: 959.9999713897713,
															pixelHeight: 720,
															pixelWidth: 1280,
															sizes: "960px",
															src: "https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?width=1280&height=720",
															srcSet:
																"https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?scale-down-to=512&width=1280&height=720 512w,https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?scale-down-to=1024&width=1280&height=720 1024w,https://framerusercontent.com/images/1jnGs8fYeFwSvQ8YvzPM4Ysocw.jpeg?width=1280&height=720 1280w",
														}}
														className={"framer-19k905t"}
														data-framer-name={
															"\xCC\xB2\xAD\xEB\x82\xA8\xEB\x8C\x802"
														}
														layoutDependency={layoutDependency}
														layoutId={"oDjY9dw8u"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 959.9999713897713,
															intrinsicWidth: 767.9999771118171,
															pixelHeight: 1280,
															pixelWidth: 1024,
															sizes: "768px",
															src: "https://framerusercontent.com/images/fMOdMuOpydr0L1DUs1ZmNaszh8.jpeg?width=1024&height=1280",
															srcSet:
																"https://framerusercontent.com/images/fMOdMuOpydr0L1DUs1ZmNaszh8.jpeg?scale-down-to=1024&width=1024&height=1280 819w,https://framerusercontent.com/images/fMOdMuOpydr0L1DUs1ZmNaszh8.jpeg?width=1024&height=1280 1024w",
														}}
														className={"framer-158o4w6"}
														data-framer-name={
															"\xCC\xB2\xAD\xEB\x82\xA8\xEB\x8C\x803"
														}
														layoutDependency={layoutDependency}
														layoutId={"aYGjhde88"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 528.7499842420225,
															intrinsicWidth: 784.4999766200788,
															pixelHeight: 705,
															pixelWidth: 1046,
															sizes: "784.8709px",
															src: "https://framerusercontent.com/images/GDj44gpxAOo55cH3RRuiOtdQ.jpeg?width=1046&height=705",
															srcSet:
																"https://framerusercontent.com/images/GDj44gpxAOo55cH3RRuiOtdQ.jpeg?scale-down-to=512&width=1046&height=705 512w,https://framerusercontent.com/images/GDj44gpxAOo55cH3RRuiOtdQ.jpeg?scale-down-to=1024&width=1046&height=705 1024w,https://framerusercontent.com/images/GDj44gpxAOo55cH3RRuiOtdQ.jpeg?width=1046&height=705 1046w",
														}}
														className={"framer-1aezjdv"}
														data-framer-name={
															"\xCC\xB2\xAD\xEB\x82\xA8\xEB\x8C\x804"
														}
														layoutDependency={layoutDependency}
														layoutId={"JOxqYPmpo"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 959.9999713897713,
															intrinsicWidth: 767.9999771118171,
															pixelHeight: 1280,
															pixelWidth: 1024,
															sizes: "768px",
															src: "https://framerusercontent.com/images/vDtfvMsi4l0w5E7F4LhSHbkNFa0.jpeg?width=1024&height=1280",
															srcSet:
																"https://framerusercontent.com/images/vDtfvMsi4l0w5E7F4LhSHbkNFa0.jpeg?scale-down-to=1024&width=1024&height=1280 819w,https://framerusercontent.com/images/vDtfvMsi4l0w5E7F4LhSHbkNFa0.jpeg?width=1024&height=1280 1024w",
														}}
														className={"framer-7b3a94"}
														data-border={true}
														data-framer-name={
															"\xCC\xB2\xAD\xEB\x82\xA8\xEB\x8C\x805"
														}
														layoutDependency={layoutDependency}
														layoutId={"pER_2YDtS"}
														style={{
															"--border-bottom-width": "1px",
															"--border-color": "rgb(34, 34, 34)",
															"--border-left-width": "1px",
															"--border-right-width": "1px",
															"--border-style": "solid",
															"--border-top-width": "1px",
														}}
													/>,
												]}
												startFrom={0}
												style={{
													height: "100%",
													width: "100%",
												}}
												transitionControl={{
													damping: 40,
													delay: 0,
													mass: 1,
													stiffness: 200,
													type: "spring",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1s6tq1i"}
								layoutDependency={layoutDependency}
								layoutId={"iS7MUhenx"}
							>
								<motion.div
									className={"framer-1jfcriw"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"DB_v1BInQ"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-c4bljj-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"TQ3Il3X_j-container"}
											nodeId={"TQ3Il3X_j"}
											rendersWithMotion={true}
											scopeId={"Cpv0tJHMt"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"\uCCAD\uB0A8\uB300"}
												height={"100%"}
												id={"TQ3Il3X_j"}
												isMixedBorderRadius={false}
												layoutId={"TQ3Il3X_j"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={15}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-4sd35f"}
									layoutDependency={layoutDependency}
									layoutId={"tZKXfzqFk"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-28prco"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"gCoa1GaKw"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8 \uC815\uBCF4"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1lzzzna"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"vdT4vFOv_"}
										style={{
											"--extracted-14qxiz": "rgb(153, 153, 153)",
											"--extracted-1ho1rsj": '"opsz" 32, "wght" 500',
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-1wc4bty": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--extracted-ydz9fi": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC8FC\uC18C : \uCDA9\uBD81 \uCCAD\uC8FC\uC2DC \uC0C1\uB2F9\uAD6C \uBB38\uC758\uBA74 \uCCAD\uB0A8\uB300\uAE38 646 \uCCAD\uB0A8\uB300\uAD00\uB9AC\uC0AC\uC5C5\uC18C"
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{"\uC601\uC5C5 \uC2DC\uAC04 :"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												{"-\uB9E4\uD45C : 09:00 - 16:30"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1wc4bty, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-14qxiz, rgb(153, 153, 153))",
												}}
											>
												{"-\uAD00\uB78C : 09:00 - 08:00"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1ho1rsj, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-ydz9fi, rgb(153, 153, 153))",
												}}
											>
												{"\uC804\uD654\uBC88\uD638 : 043-257-5080"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-tboksh"}
								layoutDependency={layoutDependency}
								layoutId={"s7vgOEuDb"}
							>
								<motion.div
									className={"framer-4bs21t"}
									layoutDependency={layoutDependency}
									layoutId={"joGs1v_MJ"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-zv9scm"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"H7fvVRYOd"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uC608\uC57D \uD558\uAE30"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-rhpeik"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"XKu2qjwYF"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-6hgnmr"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"S1hQqMUX6"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										className={"framer-11z4zho"}
										data-framer-name={"Placeholder"}
										layoutDependency={layoutDependency}
										layoutId={"S0XpFUGag"}
										style={{
											backgroundColor: "rgb(245, 245, 245)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1psmsrg-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"byA3xF3fs-container"}
												nodeId={"byA3xF3fs"}
												rendersWithMotion={true}
												scopeId={"Cpv0tJHMt"}
											>
												<Calcom
													darkTheme={"rgb(250, 250, 250)"}
													eventLink={
														"https://cal.com/framer-placeholder/default"
													}
													height={"100%"}
													id={"byA3xF3fs"}
													layout={"month_view"}
													layoutId={"byA3xF3fs"}
													lightTheme={"rgb(41, 41, 41)"}
													showEventTypeDetails={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													theme={"auto"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-K1iwW.framer-gr461s, .framer-K1iwW .framer-gr461s { display: block; }",
	".framer-K1iwW.framer-1aot3ny { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-K1iwW .framer-3rpjp0-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-K1iwW .framer-ut7mb1 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-K1iwW .framer-1c8h9pd, .framer-K1iwW .framer-tboksh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-K1iwW .framer-1ve4jd0 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-K1iwW .framer-19lsyxr, .framer-K1iwW .framer-28prco, .framer-K1iwW .framer-zv9scm { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-K1iwW .framer-1xyv070, .framer-K1iwW .framer-1lzzzna, .framer-K1iwW .framer-rhpeik { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-K1iwW .framer-132ydxw, .framer-K1iwW .framer-6hgnmr, .framer-K1iwW .framer-11z4zho { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-K1iwW .framer-1y0xmn5-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-K1iwW .framer-1uav7l5 { aspect-ratio: 1.5005861664712778 / 1; height: var(--framer-aspect-ratio-supported, 640px); overflow: visible; position: relative; width: 960px; }",
	".framer-K1iwW .framer-19k905t { aspect-ratio: 1.7777777777777777 / 1; height: var(--framer-aspect-ratio-supported, 540px); overflow: visible; position: relative; width: 960px; }",
	".framer-K1iwW .framer-158o4w6, .framer-K1iwW .framer-7b3a94 { aspect-ratio: 0.8 / 1; height: var(--framer-aspect-ratio-supported, 960px); overflow: visible; position: relative; width: 768px; }",
	".framer-K1iwW .framer-1aezjdv { aspect-ratio: 1.4836879432624113 / 1; height: var(--framer-aspect-ratio-supported, 529px); overflow: visible; position: relative; width: 785px; }",
	".framer-K1iwW .framer-1s6tq1i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-K1iwW .framer-1jfcriw { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-K1iwW .framer-c4bljj-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-K1iwW .framer-4sd35f, .framer-K1iwW .framer-4bs21t { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-K1iwW .framer-1psmsrg-container { flex: none; height: 480px; position: relative; width: 480px; }",
	'.framer-K1iwW[data-border="true"]::after, .framer-K1iwW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerCpv0tJHMt = withCSS(Component, css, "framer-K1iwW");
var stdin_default2 = FramerCpv0tJHMt;
FramerCpv0tJHMt.displayName = "cheong_choeng";
FramerCpv0tJHMt.defaultProps = {
	height: 1659,
	width: 1200,
};
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerCpv0tJHMt,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
		...GoogleMapsFonts,
		...CalComFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cheong-choeng
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CheongChoengFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cheong_choeng_default = ComponentWithRoot;
export { cheong_choeng_default as default };
