// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";
import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:cheong-myung
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b8dEf7STkKeyHISdiWRr/09MP29ZG5rXkJJuNkRPG/dvfV4iZVW.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);
var serializationHash = "framer-HrJVq";
var variantClassNames = {
	QuHgyarAl: "framer-v-ia15ox",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "QuHgyarAl",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ia15ox",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"QuHgyarAl"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-1eaat5k-container"}
								layoutDependency={layoutDependency}
								layoutId={"GWxygvmhz-container"}
								nodeId={"GWxygvmhz"}
								rendersWithMotion={true}
								scopeId={"dvfV4iZVW"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "GWxygvmhz",
									layoutId: "GWxygvmhz",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-1035inx"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"SK28tC3PM"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-jkhii"}
								layoutDependency={layoutDependency}
								layoutId={"mF_elkd9h"}
							>
								<motion.div
									className={"framer-13yb26q"}
									layoutDependency={layoutDependency}
									layoutId={"GnfzdeC3F"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-bm8doq"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"K73lkJkGJ"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uBA85\uC554\uD0C0\uC6CC"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-afqtce"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"umB8nf9WB"}
										style={{
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCDA9\uCCAD\uBD81\uB3C4 \uCCAD\uC8FC\uC2DC \uC0C1\uB2F9\uAD6C \uC6A9\uB2F4\uB3D9\xA0\uC6A9\uC554\uC9C0 \uC606\uC5D0 \uC788\uB294 \uAD00\uB9DD\uD0D1."
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{
													"2001\uB144 \uBA85\uC554\uC9C0\uC758 \uC778\uADFC \uC2DC\uC720\uC9C0\uC758 \uC720\uC6D0\uC9C0 \uAC1C\uBC1C\uC0AC\uC5C5\uC5D0 \uCC29\uC218\uD558\uC600\uB2E4. \uC2DC\uC720\uC9C0 8,138\u33A1 \uBD80\uC9C0\uC5D0 \uBBFC\uC790\uB97C \uC720\uCE58\uD558\uC5EC 2001\uB144 12\uC6D4 28\uC77C \uAD00\uB9DD\uD0D1 \uACF5\uC0AC\uB97C \uC2DC\uC791\uD558\uC5EC 2003\uB144 12\uC6D4 19\uC77C \uBA85\uC554\uD0C0\uC6CC\uB780 \uC774\uB984\uC73C\uB85C \uC900\uACF5\uB418\uC5C8\uB2E4."
												}
												<motion.br />
												<motion.br className={"trailing-break"} />
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-lc9z6r"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"RMJ8nnDQc"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-am4idq-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"aVyaWoC10-container"}
											nodeId={"aVyaWoC10"}
											rendersWithMotion={true}
											scopeId={"dvfV4iZVW"}
										>
											<Slideshow
												alignment={"center"}
												arrowOptions={{
													arrowFill: "rgba(0, 0, 0, 0.2)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: 0,
													arrowPosition: "auto",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: true,
													arrowSize: 40,
													showMouseControls: true,
												}}
												autoPlayControl={true}
												borderRadius={0}
												direction={"left"}
												dragControl={false}
												effectsOptions={{
													effectsHover: true,
													effectsOpacity: 1,
													effectsPerspective: 1200,
													effectsRotate: 0,
													effectsScale: 1,
													playOffscreen: false,
												}}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												id={"aVyaWoC10"}
												intervalControl={2.5}
												itemAmount={1}
												layoutId={"aVyaWoC10"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												progressOptions={{
													dotsActiveOpacity: 1,
													dotsBackground: "rgba(0, 0, 0, 0.2)",
													dotsBlur: 0,
													dotsFill: "rgb(255, 255, 255)",
													dotsGap: 10,
													dotsInset: 10,
													dotSize: 10,
													dotsOpacity: 0.5,
													dotsPadding: 10,
													dotsRadius: 50,
													showProgressDots: true,
												}}
												slots={[
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 959.9999713897713,
															intrinsicWidth: 639.7499809339648,
															pixelHeight: 1280,
															pixelWidth: 853,
															sizes: "640px",
															src: "https://framerusercontent.com/images/I5xwLrUW3NgTLHjCjBgQ2s6Ag.jpeg?width=853&height=1280",
															srcSet:
																"https://framerusercontent.com/images/I5xwLrUW3NgTLHjCjBgQ2s6Ag.jpeg?scale-down-to=1024&width=853&height=1280 682w,https://framerusercontent.com/images/I5xwLrUW3NgTLHjCjBgQ2s6Ag.jpeg?width=853&height=1280 853w",
														}}
														className={"framer-1948pf6"}
														data-framer-name={"\xCB\xAA\x85\xEC\x95\x941"}
														layoutDependency={layoutDependency}
														layoutId={"IKSxZGkaf"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 959.9999713897713,
															intrinsicWidth: 719.9999785423286,
															pixelHeight: 1280,
															pixelWidth: 960,
															sizes: "720px",
															src: "https://framerusercontent.com/images/fvBzLlbQwt9BM4oqzAKPnTdmRY.jpeg?width=960&height=1280",
															srcSet:
																"https://framerusercontent.com/images/fvBzLlbQwt9BM4oqzAKPnTdmRY.jpeg?scale-down-to=1024&width=960&height=1280 768w,https://framerusercontent.com/images/fvBzLlbQwt9BM4oqzAKPnTdmRY.jpeg?width=960&height=1280 960w",
														}}
														className={"framer-12mtis3"}
														data-framer-name={"\xCB\xAA\x85\xEC\x95\x942"}
														layoutDependency={layoutDependency}
														layoutId={"Rs9JPRKpG"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 959.9999713897713,
															intrinsicWidth: 719.9999785423286,
															pixelHeight: 1280,
															pixelWidth: 960,
															sizes: "720px",
															src: "https://framerusercontent.com/images/NPt7KPzunEMkbksGCDHBAWczQDA.jpeg?width=960&height=1280",
															srcSet:
																"https://framerusercontent.com/images/NPt7KPzunEMkbksGCDHBAWczQDA.jpeg?scale-down-to=1024&width=960&height=1280 768w,https://framerusercontent.com/images/NPt7KPzunEMkbksGCDHBAWczQDA.jpeg?width=960&height=1280 960w",
														}}
														className={"framer-k967dl"}
														data-framer-name={"\xCB\xAA\x85\xEC\x82\xAC5"}
														layoutDependency={layoutDependency}
														layoutId={"nzeW9ZAC6"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 639.7499809339648,
															intrinsicWidth: 959.9999713897713,
															pixelHeight: 853,
															pixelWidth: 1280,
															sizes: "960.3751px",
															src: "https://framerusercontent.com/images/t6ofWpNNSYrK4znUspQvsFdLbyg.jpeg?width=1280&height=853",
															srcSet:
																"https://framerusercontent.com/images/t6ofWpNNSYrK4znUspQvsFdLbyg.jpeg?scale-down-to=512&width=1280&height=853 512w,https://framerusercontent.com/images/t6ofWpNNSYrK4znUspQvsFdLbyg.jpeg?scale-down-to=1024&width=1280&height=853 1024w,https://framerusercontent.com/images/t6ofWpNNSYrK4znUspQvsFdLbyg.jpeg?width=1280&height=853 1280w",
														}}
														className={"framer-1076mxo"}
														data-framer-name={"\xCB\xAA\x85\xEC\x82\xAC4"}
														layoutDependency={layoutDependency}
														layoutId={"irzWGlprc"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															intrinsicHeight: 539.9999839067464,
															intrinsicWidth: 959.9999713897713,
															pixelHeight: 720,
															pixelWidth: 1280,
															sizes: "960px",
															src: "https://framerusercontent.com/images/zWv9zbmH1hGvsvXSIeLsdMwaCas.jpeg?width=1280&height=720",
															srcSet:
																"https://framerusercontent.com/images/zWv9zbmH1hGvsvXSIeLsdMwaCas.jpeg?scale-down-to=512&width=1280&height=720 512w,https://framerusercontent.com/images/zWv9zbmH1hGvsvXSIeLsdMwaCas.jpeg?scale-down-to=1024&width=1280&height=720 1024w,https://framerusercontent.com/images/zWv9zbmH1hGvsvXSIeLsdMwaCas.jpeg?width=1280&height=720 1280w",
														}}
														className={"framer-15qfiyt"}
														data-framer-name={"\xCB\xAA\x85\xEC\x95\x943"}
														layoutDependency={layoutDependency}
														layoutId={"lGBJJ9MTk"}
													/>,
												]}
												startFrom={0}
												style={{
													height: "100%",
													width: "100%",
												}}
												transitionControl={{
													damping: 40,
													delay: 0,
													mass: 1,
													stiffness: 200,
													type: "spring",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1t556xm"}
								layoutDependency={layoutDependency}
								layoutId={"OTJFPwa_2"}
							>
								<motion.div
									className={"framer-s2nv7c"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"xs4yn3EWs"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-ufsjmh-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"DYdzgXhEB-container"}
											nodeId={"DYdzgXhEB"}
											rendersWithMotion={true}
											scopeId={"dvfV4iZVW"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"\uBA85\uC554\uD0C0\uC6CC"}
												height={"100%"}
												id={"DYdzgXhEB"}
												isMixedBorderRadius={false}
												layoutId={"DYdzgXhEB"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={15}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-10k46pc"}
									layoutDependency={layoutDependency}
									layoutId={"sbT0Cd09d"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-kgiipv"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"zySWgcXar"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8 \uC815\uBCF4"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-18xrqi0"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"Cx9bzOhGr"}
										style={{
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC8FC\uC18C : \uCDA9\uBD81 \uCCAD\uC8FC\uC2DC \uC0C1\uB2F9\uAD6C 1\uC21C\uD658\uB85C 1685-31"
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{"\uC6B4\uC601 \uC2DC\uAC04 : 24\uC2DC\uAC04"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												{"\uC804\uD654\uBC88\uD638 : 043-201-2753"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1w2dqcn"}
								layoutDependency={layoutDependency}
								layoutId={"nDVUrjPu2"}
							>
								<motion.div
									className={"framer-ddzfr6"}
									layoutDependency={layoutDependency}
									layoutId={"uG31GbDKH"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1qt32fj"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"ZHlvNaeAF"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uC608\uC57D \uD558\uAE30"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-mvqkuu"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"xiJp_jl9k"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1ifkj90"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"GsOIHjLl8"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										className={"framer-18c6eu8"}
										data-framer-name={"Placeholder"}
										layoutDependency={layoutDependency}
										layoutId={"CIX6Rmk__"}
										style={{
											backgroundColor: "rgb(245, 245, 245)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-1tup6b6-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"Me4Rg2YL5-container"}
												nodeId={"Me4Rg2YL5"}
												rendersWithMotion={true}
												scopeId={"dvfV4iZVW"}
											>
												<Calcom
													darkTheme={"rgb(250, 250, 250)"}
													eventLink={
														"https://cal.com/framer-placeholder/default"
													}
													height={"100%"}
													id={"Me4Rg2YL5"}
													layout={"month_view"}
													layoutId={"Me4Rg2YL5"}
													lightTheme={"rgb(41, 41, 41)"}
													showEventTypeDetails={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													theme={"auto"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HrJVq.framer-1fhfr61, .framer-HrJVq .framer-1fhfr61 { display: block; }",
	".framer-HrJVq.framer-ia15ox { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-HrJVq .framer-1eaat5k-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-HrJVq .framer-1035inx { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-HrJVq .framer-jkhii, .framer-HrJVq .framer-1w2dqcn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-HrJVq .framer-13yb26q { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-HrJVq .framer-bm8doq, .framer-HrJVq .framer-kgiipv, .framer-HrJVq .framer-1qt32fj { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-HrJVq .framer-afqtce, .framer-HrJVq .framer-18xrqi0, .framer-HrJVq .framer-mvqkuu { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-HrJVq .framer-lc9z6r, .framer-HrJVq .framer-1ifkj90, .framer-HrJVq .framer-18c6eu8 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-HrJVq .framer-am4idq-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-HrJVq .framer-1948pf6 { aspect-ratio: 0.6664062500000001 / 1; height: var(--framer-aspect-ratio-supported, 961px); overflow: visible; position: relative; width: 640px; }",
	".framer-HrJVq .framer-12mtis3, .framer-HrJVq .framer-k967dl { aspect-ratio: 0.7500000000000001 / 1; height: var(--framer-aspect-ratio-supported, 960px); overflow: visible; position: relative; width: 720px; }",
	".framer-HrJVq .framer-1076mxo { aspect-ratio: 1.5005861664712778 / 1; height: var(--framer-aspect-ratio-supported, 640px); overflow: visible; position: relative; width: 960px; }",
	".framer-HrJVq .framer-15qfiyt { aspect-ratio: 1.7777777777777777 / 1; height: var(--framer-aspect-ratio-supported, 540px); overflow: visible; position: relative; width: 960px; }",
	".framer-HrJVq .framer-1t556xm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-HrJVq .framer-s2nv7c { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-HrJVq .framer-ufsjmh-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-HrJVq .framer-10k46pc, .framer-HrJVq .framer-ddzfr6 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-HrJVq .framer-1tup6b6-container { flex: none; height: 480px; position: relative; width: 480px; }",
];
var FramerdvfV4iZVW = withCSS(Component, css, "framer-HrJVq");
var stdin_default2 = FramerdvfV4iZVW;
FramerdvfV4iZVW.displayName = "cheong_myung";
FramerdvfV4iZVW.defaultProps = {
	height: 1659,
	width: 1200,
};
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerdvfV4iZVW,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
		...GoogleMapsFonts,
		...CalComFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cheong-myung
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CheongMyungFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cheong_myung_default = ComponentWithRoot;
export { cheong_myung_default as default };
