// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";
import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:kang-git
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/SvOTcCx9JjYRa932wynU/Etm472S72IKdzfIobe4B/nSRPupnG2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);
var serializationHash = "framer-8nhGu";
var variantClassNames = {
	JTMIqoiEy: "framer-v-tlgdgs",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "JTMIqoiEy",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-tlgdgs",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"JTMIqoiEy"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-1kke2d7-container"}
								layoutDependency={layoutDependency}
								layoutId={"yqQXJ2f2v-container"}
								nodeId={"yqQXJ2f2v"}
								rendersWithMotion={true}
								scopeId={"nSRPupnG2"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "yqQXJ2f2v",
									layoutId: "yqQXJ2f2v",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-f1j1s5"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"SabKgBdEl"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-1iz8ydn"}
								layoutDependency={layoutDependency}
								layoutId={"Tww1iB9cT"}
							>
								<motion.div
									className={"framer-tqf6i9"}
									layoutDependency={layoutDependency}
									layoutId={"YybBlWCPA"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1vagumm"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"MDZFrD9ZI"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uCE74\uD398 \uAE37"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1aym99v"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"iEwspASBe"}
										style={{
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "29px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE74\uD398 \uAE37\uC740 \uC6B8\uC0B0\uBC14\uC704 \uBDF0\uC640 \uD568\uAED8 \uD2B9\uBCC4\uD55C \uCEE4\uD53C\uC640 \uB514\uC800\uD2B8\uB97C \uC990\uAE38 \uC218 \uC788\uB294 \uC18D\uCD08\uC758 \uB300\uD615 \uCE74\uD398\uC785\uB2C8\uB2E4.\uC778\uAE30 \uBA54\uB274\uC778 \uBC84\uD130 \uD06C\uB9AC\uBBF8\uC640 \uC6B8\uC0B0\uBC14\uC704 \uB77C\uB5BC, \uADF8\uB9AC\uACE0 \uC625\uC218\uC218 \uC544\uC774\uC2A4\uD06C\uB9BC\uC774 \uC778\uAE30 \uC788\uC73C\uBA70, \uCE35\uACE0 \uB192\uC740 \uC2E4\uB0B4\uC640 \uB113\uC740 \uC8FC\uCC28\uC7A5, \uC57C\uC678 \uC88C\uC11D\uC5D0\uC11C \uC124\uC545\uC0B0 \uD48D\uACBD\uC744 \uAC10\uC0C1\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4."
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "29px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC720\uBAA8\uCC28 \uC9C4\uC785\uC774 \uAC00\uB2A5\uD574 \uAC00\uC871 \uB2E8\uC704 \uBC29\uBB38\uAC1D\uC5D0\uAC8C\uB3C4 \uC801\uD569\uD569\uB2C8\uB2E4."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1kzjtzv"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"is2iFHWiR"}
									style={{
										backgroundColor: "rgb(255, 255, 255)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-b9i2sg-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"MkV3F3KIt-container"}
											nodeId={"MkV3F3KIt"}
											rendersWithMotion={true}
											scopeId={"nSRPupnG2"}
										>
											<Slideshow
												alignment={"center"}
												arrowOptions={{
													arrowFill: "rgba(0, 0, 0, 0.2)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: 0,
													arrowPosition: "auto",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: true,
													arrowSize: 40,
													showMouseControls: true,
												}}
												autoPlayControl={true}
												borderRadius={0}
												direction={"left"}
												dragControl={false}
												effectsOptions={{
													effectsHover: true,
													effectsOpacity: 1,
													effectsPerspective: 1200,
													effectsRotate: 0,
													effectsScale: 1,
													playOffscreen: false,
												}}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												id={"MkV3F3KIt"}
												intervalControl={2.5}
												itemAmount={1}
												layoutId={"MkV3F3KIt"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												progressOptions={{
													dotsActiveOpacity: 1,
													dotsBackground: "rgba(0, 0, 0, 0.2)",
													dotsBlur: 0,
													dotsFill: "rgb(255, 255, 255)",
													dotsGap: 10,
													dotsInset: 10,
													dotSize: 10,
													dotsOpacity: 0.5,
													dotsPadding: 10,
													dotsRadius: 50,
													showProgressDots: true,
												}}
												slots={[
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 1162,
															pixelWidth: 1262,
															sizes: "400px",
															src: "https://framerusercontent.com/images/d7nJyIEkJNCJ7CekyRBX18ah1w.png?width=1262&height=1162",
															srcSet:
																"https://framerusercontent.com/images/d7nJyIEkJNCJ7CekyRBX18ah1w.png?scale-down-to=512&width=1262&height=1162 512w,https://framerusercontent.com/images/d7nJyIEkJNCJ7CekyRBX18ah1w.png?scale-down-to=1024&width=1262&height=1162 1024w,https://framerusercontent.com/images/d7nJyIEkJNCJ7CekyRBX18ah1w.png?width=1262&height=1162 1262w",
														}}
														className={"framer-15vly2d"}
														layoutDependency={layoutDependency}
														layoutId={"FQviMWAVn"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 1132,
															pixelWidth: 1090,
															sizes: "400px",
															src: "https://framerusercontent.com/images/6NywbDgDO3HbTys3jeHH0w6hbek.png?width=1090&height=1132",
															srcSet:
																"https://framerusercontent.com/images/6NywbDgDO3HbTys3jeHH0w6hbek.png?scale-down-to=1024&width=1090&height=1132 986w,https://framerusercontent.com/images/6NywbDgDO3HbTys3jeHH0w6hbek.png?width=1090&height=1132 1090w",
														}}
														className={"framer-bc3rbq"}
														layoutDependency={layoutDependency}
														layoutId={"pZ5o5tMr3"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 1096,
															pixelWidth: 1472,
															sizes: "400px",
															src: "https://framerusercontent.com/images/NGCFBEjqxa53vYutCqWglwV8.png?width=1472&height=1096",
															srcSet:
																"https://framerusercontent.com/images/NGCFBEjqxa53vYutCqWglwV8.png?scale-down-to=512&width=1472&height=1096 512w,https://framerusercontent.com/images/NGCFBEjqxa53vYutCqWglwV8.png?scale-down-to=1024&width=1472&height=1096 1024w,https://framerusercontent.com/images/NGCFBEjqxa53vYutCqWglwV8.png?width=1472&height=1096 1472w",
														}}
														className={"framer-ph4n35"}
														layoutDependency={layoutDependency}
														layoutId={"qnFk0gPKP"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 1362,
															pixelWidth: 1352,
															sizes: "400px",
															src: "https://framerusercontent.com/images/ronDrQan5KBOqO5TG27hImuX1Y.png?width=1352&height=1362",
															srcSet:
																"https://framerusercontent.com/images/ronDrQan5KBOqO5TG27hImuX1Y.png?scale-down-to=1024&width=1352&height=1362 1016w,https://framerusercontent.com/images/ronDrQan5KBOqO5TG27hImuX1Y.png?width=1352&height=1362 1352w",
														}}
														className={"framer-kj6mnd"}
														layoutDependency={layoutDependency}
														layoutId={"juDV8bwfK"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 750,
															pixelWidth: 750,
															sizes: "400px",
															src: "https://framerusercontent.com/images/gQejPk8JjyJeoONIbOCHe1O24U4.webp?width=750&height=750",
															srcSet:
																"https://framerusercontent.com/images/gQejPk8JjyJeoONIbOCHe1O24U4.webp?scale-down-to=512&width=750&height=750 512w,https://framerusercontent.com/images/gQejPk8JjyJeoONIbOCHe1O24U4.webp?width=750&height=750 750w",
														}}
														className={"framer-f880r4"}
														layoutDependency={layoutDependency}
														layoutId={"m5aoJyNnw"}
													/>,
												]}
												startFrom={0}
												style={{
													height: "100%",
													width: "100%",
												}}
												transitionControl={{
													damping: 40,
													delay: 0,
													mass: 1,
													stiffness: 200,
													type: "spring",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-l6erun"}
								layoutDependency={layoutDependency}
								layoutId={"bVyNGEvtY"}
							>
								<motion.div
									className={"framer-1at3rqx"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"j468ZBqwd"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-7fr1c6-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"hn6JmIZO5-container"}
											nodeId={"hn6JmIZO5"}
											rendersWithMotion={true}
											scopeId={"nSRPupnG2"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"\uCE74\uD398 \uAE37"}
												height={"100%"}
												id={"hn6JmIZO5"}
												isMixedBorderRadius={false}
												layoutId={"hn6JmIZO5"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={13}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1vh1jqn"}
									layoutDependency={layoutDependency}
									layoutId={"NmZ3Vb71m"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-wjaqph"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"fS_mfePhH"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										transformTemplate={transformTemplate1}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8 \uC815\uBCF4 "}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-13mbii3"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"uTh3QH597"}
										style={{
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										transformTemplate={transformTemplate1}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC8FC\uC18C : \uAC15\uC6D0 \uC18D\uCD08\uC2DC \uC6D0\uC554\uD559\uC0AC\uD3C9\uAE38 60 "
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{"\uC601\uC5C5 \uC2DC\uAC04 : 10:30 ~ 18:00"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												{"\uC804\uD654\uBC88\uD638 : 0507-1362-4043"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1j7flke"}
								layoutDependency={layoutDependency}
								layoutId={"rGDfGcQ6R"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-174v4nw"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"HxWZZTuyA"}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "32px",
											}}
										>
											{"\uC608\uC57D \uD558\uAE30"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-w1zmdu"}
									layoutDependency={layoutDependency}
									layoutId={"lChgi5dQ7"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1s4ueq6"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"xyhExL26q"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-196bboa"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"xr953HgCg"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										className={"framer-1bt4w9c"}
										data-framer-name={"Placeholder"}
										layoutDependency={layoutDependency}
										layoutId={"o_i13mF4b"}
										style={{
											backgroundColor: "rgb(245, 245, 245)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-13zq8nu-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"vzn1pt1pj-container"}
												nodeId={"vzn1pt1pj"}
												rendersWithMotion={true}
												scopeId={"nSRPupnG2"}
											>
												<Calcom
													darkTheme={"rgb(250, 250, 250)"}
													eventLink={
														"https://cal.com/framer-placeholder/default"
													}
													height={"100%"}
													id={"vzn1pt1pj"}
													layout={"month_view"}
													layoutId={"vzn1pt1pj"}
													lightTheme={"rgb(41, 41, 41)"}
													showEventTypeDetails={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													theme={"auto"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8nhGu.framer-137k4yj, .framer-8nhGu .framer-137k4yj { display: block; }",
	".framer-8nhGu.framer-tlgdgs { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-8nhGu .framer-1kke2d7-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-8nhGu .framer-f1j1s5 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: var(--overflow-clip-fallback, clip); padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-8nhGu .framer-1iz8ydn, .framer-8nhGu .framer-1j7flke { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-8nhGu .framer-tqf6i9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8nhGu .framer-1vagumm { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-8nhGu .framer-1aym99v { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 369px; word-break: break-word; word-wrap: break-word; }",
	".framer-8nhGu .framer-1kzjtzv, .framer-8nhGu .framer-196bboa, .framer-8nhGu .framer-1bt4w9c { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8nhGu .framer-b9i2sg-container { bottom: 0px; flex: none; position: absolute; right: 0px; top: 0px; width: 475px; z-index: 1; }",
	".framer-8nhGu .framer-15vly2d, .framer-8nhGu .framer-bc3rbq, .framer-8nhGu .framer-ph4n35, .framer-8nhGu .framer-kj6mnd, .framer-8nhGu .framer-f880r4 { height: 300px; position: relative; width: 400px; }",
	".framer-8nhGu .framer-l6erun { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 960px; }",
	".framer-8nhGu .framer-1at3rqx { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8nhGu .framer-7fr1c6-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-8nhGu .framer-1vh1jqn { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 69px; overflow: visible; padding: 0px; position: sticky; top: 0px; width: 1px; z-index: 1; }",
	".framer-8nhGu .framer-wjaqph { flex: none; height: auto; left: 50%; max-width: 100%; position: absolute; top: -16px; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-8nhGu .framer-13mbii3 { --framer-text-wrap: balance; bottom: -38px; flex: none; height: auto; left: 50%; max-width: 100%; position: absolute; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-8nhGu .framer-174v4nw { flex: none; height: auto; left: 79px; position: absolute; top: 184px; white-space: pre; width: auto; z-index: 1; }",
	".framer-8nhGu .framer-w1zmdu { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-8nhGu .framer-1s4ueq6 { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-8nhGu .framer-13zq8nu-container { flex: none; height: 480px; position: relative; width: 480px; }",
];
var FramernSRPupnG2 = withCSS(Component, css, "framer-8nhGu");
var stdin_default2 = FramernSRPupnG2;
FramernSRPupnG2.displayName = "kang_git";
FramernSRPupnG2.defaultProps = {
	height: 1659,
	width: 1200,
};
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramernSRPupnG2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
		...GoogleMapsFonts,
		...CalComFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:kang-git
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders KangGitFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var kang_git_default = ComponentWithRoot;
export { kang_git_default as default };
