// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3759d569955c51a9 "Perform (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Calcom } from "./chunks/chunk-N54VTD32.js";
import { GoogleMaps } from "./chunks/chunk-WJ4M4KHJ.js";
import { Slideshow } from "./chunks/chunk-FET5STFD.js";
import { stdin_default } from "./chunks/chunk-U6ARRNOW.js";
import { routes } from "./chunks/chunk-RX5K52XN.js";

// virtual:mu-hang
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/46Y9EvntiDpDyz4oh7wT/fm8MKHyoMHM44tRsTNwE/Gmt8DuPBe.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Navigation3Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var GoogleMapsFonts = getFonts(GoogleMaps);
var CalComFonts = getFonts(Calcom);
var serializationHash = "framer-jssiN";
var variantClassNames = {
	j2mmspzSE: "framer-v-i4yvdr",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "j2mmspzSE",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-i4yvdr",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"j2mmspzSE"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-1vxpiwh-container"}
								layoutDependency={layoutDependency}
								layoutId={"DVh3iwwOB-container"}
								nodeId={"DVh3iwwOB"}
								rendersWithMotion={true}
								scopeId={"Gmt8DuPBe"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "DVh3iwwOB",
									layoutId: "DVh3iwwOB",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-r7mh0p"}
							data-framer-name={"Features"}
							layoutDependency={layoutDependency}
							layoutId={"ouQkKyofu"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
							transformTemplate={transformTemplate1}
						>
							<motion.div
								className={"framer-qpwvg7"}
								layoutDependency={layoutDependency}
								layoutId={"A11Tk9VPo"}
							>
								<motion.div
									className={"framer-1d6lk3o"}
									layoutDependency={layoutDependency}
									layoutId={"MBgNX5xAc"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-105tqhv"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"LTobi1Ffw"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uD5A5\uC801\uBD09(\uB355\uC720\uC0B0)"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-p00oj8"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"TikJ5tISl"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "25px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uB355\uC720\uC0B0\uC740 \uC804\uBD81 \uBB34\uC8FC\xB7\uC7A5\uC218\uC640 \uACBD\uB0A8 \uAC70\uCC3D\xB7\uD568\uC591\uC5D0 \uAC78\uCE5C \uD574\uBC1C 1,614m\uC758 \uC0B0\uC785\uB2C8\uB2E4. \uACA8\uC6B8\uCCA0\uC5D0\uB294 \uB208\uC774 \uB9CE\uC774 \uB0B4\uB824 \uC124\uACBD\uC774 \uC544\uB984\uB2F5\uACE0, \uC0B0\uC545\uC778\uB4E4 \uC0AC\uC774\uC5D0\uC11C\uB294 100\uB300 \uBA85\uC0B0 \uC911 \uD558\uB098\uB85C \uC720\uBA85\uD569\uB2C8\uB2E4. \uD5A5\uC801\uBD09\uC740 \uB355\uC720\uC0B0\uC758 \uCD5C\uACE0\uBD09\uC73C\uB85C \uB0A8\uD55C\uC5D0\uC11C \uB124 \uBC88\uC9F8\uB85C \uB192\uC740 \uBD09\uC6B0\uB9AC\uC774\uBA70, \uACE4\uB3CC\uB77C\uB97C \uC774\uC6A9\uD55C \uC124\uCC9C\uBD09~\uD5A5\uC801\uBD09 \uAD6C\uAC04\uC740 \uC9E7\uC740 \uCF54\uC2A4\uB85C \uC778\uAE30\uAC00 \uB9CE\uC2B5\uB2C8\uB2E4."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-u54e1k"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"FfMbjebMT"}
									style={{
										backgroundColor: "rgb(255, 255, 255)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1vgeupd-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"uaj_ASGV8-container"}
											nodeId={"uaj_ASGV8"}
											rendersWithMotion={true}
											scopeId={"Gmt8DuPBe"}
										>
											<Slideshow
												alignment={"center"}
												arrowOptions={{
													arrowFill: "rgba(0, 0, 0, 0.2)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: 0,
													arrowPosition: "auto",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: true,
													arrowSize: 40,
													showMouseControls: true,
												}}
												autoPlayControl={true}
												borderRadius={0}
												direction={"left"}
												dragControl={false}
												effectsOptions={{
													effectsHover: true,
													effectsOpacity: 1,
													effectsPerspective: 1200,
													effectsRotate: 0,
													effectsScale: 1,
													playOffscreen: false,
												}}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												id={"uaj_ASGV8"}
												intervalControl={2.5}
												itemAmount={1}
												layoutId={"uaj_ASGV8"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												progressOptions={{
													dotsActiveOpacity: 1,
													dotsBackground: "rgba(0, 0, 0, 0.2)",
													dotsBlur: 0,
													dotsFill: "rgb(255, 255, 255)",
													dotsGap: 10,
													dotsInset: 10,
													dotSize: 10,
													dotsOpacity: 0.5,
													dotsPadding: 10,
													dotsRadius: 50,
													showProgressDots: true,
												}}
												slots={[
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 382,
															pixelWidth: 586,
															sizes: "400px",
															src: "https://framerusercontent.com/images/wwlDD4GYEGOEKnB0E6laHWUCjKg.jpg?width=586&height=382",
															srcSet:
																"https://framerusercontent.com/images/wwlDD4GYEGOEKnB0E6laHWUCjKg.jpg?scale-down-to=512&width=586&height=382 512w,https://framerusercontent.com/images/wwlDD4GYEGOEKnB0E6laHWUCjKg.jpg?width=586&height=382 586w",
														}}
														className={"framer-5bompn"}
														layoutDependency={layoutDependency}
														layoutId={"hRkDm08t1"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 522,
															pixelWidth: 840,
															sizes: "400px",
															src: "https://framerusercontent.com/images/7qDmbkZcOXhFcdxdTr9TKxKTA.jpg?width=840&height=522",
															srcSet:
																"https://framerusercontent.com/images/7qDmbkZcOXhFcdxdTr9TKxKTA.jpg?scale-down-to=512&width=840&height=522 512w,https://framerusercontent.com/images/7qDmbkZcOXhFcdxdTr9TKxKTA.jpg?width=840&height=522 840w",
														}}
														className={"framer-1wyzhrl"}
														layoutDependency={layoutDependency}
														layoutId={"dw6qJlSqR"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 465,
															pixelWidth: 711,
															sizes: "400px",
															src: "https://framerusercontent.com/images/4Uictkf17lzI4MKIcUPsIXitc.jpg?width=711&height=465",
															srcSet:
																"https://framerusercontent.com/images/4Uictkf17lzI4MKIcUPsIXitc.jpg?scale-down-to=512&width=711&height=465 512w,https://framerusercontent.com/images/4Uictkf17lzI4MKIcUPsIXitc.jpg?width=711&height=465 711w",
														}}
														className={"framer-1t3o5ea"}
														layoutDependency={layoutDependency}
														layoutId={"L8fvxk46f"}
													/>,
													<Image
														background={{
															alt: "",
															fit: "fill",
															pixelHeight: 472,
															pixelWidth: 706,
															sizes: "400px",
															src: "https://framerusercontent.com/images/KyGVJcJre7dWgC8MJydVwmE5PY.jpg?width=706&height=472",
															srcSet:
																"https://framerusercontent.com/images/KyGVJcJre7dWgC8MJydVwmE5PY.jpg?scale-down-to=512&width=706&height=472 512w,https://framerusercontent.com/images/KyGVJcJre7dWgC8MJydVwmE5PY.jpg?width=706&height=472 706w",
														}}
														className={"framer-itynrh"}
														layoutDependency={layoutDependency}
														layoutId={"S5Ig7KNJK"}
													/>,
												]}
												startFrom={0}
												style={{
													height: "100%",
													width: "100%",
												}}
												transitionControl={{
													damping: 40,
													delay: 0,
													mass: 1,
													stiffness: 200,
													type: "spring",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1pokmp6"}
								layoutDependency={layoutDependency}
								layoutId={"T38xYxy5l"}
							>
								<motion.div
									className={"framer-1ohe3dd"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"xrkNxfrzy"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-4ijeku-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"LUisi5bIa-container"}
											nodeId={"LUisi5bIa"}
											rendersWithMotion={true}
											scopeId={"Gmt8DuPBe"}
										>
											<GoogleMaps
												borderRadius={0}
												bottomLeftRadius={0}
												bottomRightRadius={0}
												coordinates={"\uD5A5\uC801\uBD09"}
												height={"100%"}
												id={"LUisi5bIa"}
												isMixedBorderRadius={false}
												layoutId={"LUisi5bIa"}
												style={{
													height: "100%",
													width: "100%",
												}}
												topLeftRadius={0}
												topRightRadius={0}
												width={"100%"}
												zoom={12}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-dvutxs"}
									layoutDependency={layoutDependency}
									layoutId={"rNx6aWdCK"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-qbul5f"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"iDoNQNvvq"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uAE30\uBCF8\uC815\uBCF4"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-15rf3x5"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"AEU6_hQQ9"}
										style={{
											"--extracted-1iakedh": "rgb(153, 153, 153)",
											"--extracted-1qhja7k": '"opsz" 32, "wght" 500',
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-2gxw0f": "rgb(153, 153, 153)",
											"--extracted-l7dsdt": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uC8FC\uC18C : \uBB34\uC8FC\uB355\uC720\uC0B0\uB9AC\uC870\uD2B8 \uACE4\uB3CC\uB77C \uB9E4\uD45C\uC18C(\uC804\uBD81 \uBB34\uC8FC\uAD70 \uC124\uCC9C\uBA74 \uB9CC\uC120\uB85C 185) "
												}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-1qhja7k, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(153, 153, 153))",
												}}
											>
												{"\uC601\uC5C5 \uC2DC\uAC04 : 10:00 ~ 16:00 "}
											</motion.p>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-l7dsdt, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(153, 153, 153))",
												}}
											>
												{"\uC804\uD654\uBC88\uD638 : 063-322-3174"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-k2dws3"}
								layoutDependency={layoutDependency}
								layoutId={"BMhN2X7t3"}
							>
								<motion.div
									className={"framer-lqk0ha"}
									layoutDependency={layoutDependency}
									layoutId={"RwzQgnA3P"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-jdgfp"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"BSaMT3Y4C"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 700',
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOekF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv01' on, 'cv09' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "32px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 700)',
													"--framer-letter-spacing": "-0.03em",
													"--framer-line-height": "1em",
													"--framer-text-alignment": "left",
												}}
											>
												{"\uC608\uC57D \uD558\uAE30"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-e42qoi"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"Ug52keFxv"}
										style={{
											"--extracted-2gg91v": '"opsz" 32, "wght" 500',
											"--extracted-r6o4lv": "rgb(153, 153, 153)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-open-type-features":
														"'cv09' on, 'cv01' on, 'cv05' on, 'ss03' on",
													"--framer-font-size": "22px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 32, "wght" 500)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(153, 153, 153))",
												}}
											>
												{
													"\uCE98\uB9B0\uB354\uB97C \uD074\uB9AD\uD558\uC138\uC694."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1snfza3"}
									data-framer-name={"Placeholder"}
									layoutDependency={layoutDependency}
									layoutId={"an1gnQaQh"}
									style={{
										backgroundColor: "rgb(245, 245, 245)",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<motion.div
										className={"framer-1s0hx7j"}
										data-framer-name={"Placeholder"}
										layoutDependency={layoutDependency}
										layoutId={"jHX_v0U2T"}
										style={{
											backgroundColor: "rgb(245, 245, 245)",
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-13tlijn-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"EqA_N2Veq-container"}
												nodeId={"EqA_N2Veq"}
												rendersWithMotion={true}
												scopeId={"Gmt8DuPBe"}
											>
												<Calcom
													darkTheme={"rgb(250, 250, 250)"}
													eventLink={
														"https://cal.com/framer-placeholder/default"
													}
													height={"100%"}
													id={"EqA_N2Veq"}
													layout={"month_view"}
													layoutId={"EqA_N2Veq"}
													lightTheme={"rgb(41, 41, 41)"}
													showEventTypeDetails={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													theme={"auto"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-jssiN.framer-11jo5g5, .framer-jssiN .framer-11jo5g5 { display: block; }",
	".framer-jssiN.framer-i4yvdr { height: 1659px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-jssiN .framer-1vxpiwh-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; }",
	".framer-jssiN .framer-r7mh0p { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 80px 20px 80px 20px; position: absolute; width: 100%; }",
	".framer-jssiN .framer-qpwvg7, .framer-jssiN .framer-k2dws3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-jssiN .framer-1d6lk3o { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-jssiN .framer-105tqhv, .framer-jssiN .framer-qbul5f, .framer-jssiN .framer-jdgfp { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-jssiN .framer-p00oj8, .framer-jssiN .framer-15rf3x5, .framer-jssiN .framer-e42qoi { --framer-text-wrap: balance; flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 320px; word-break: break-word; word-wrap: break-word; }",
	".framer-jssiN .framer-u54e1k, .framer-jssiN .framer-1snfza3, .framer-jssiN .framer-1s0hx7j { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 480px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-jssiN .framer-1vgeupd-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-jssiN .framer-5bompn, .framer-jssiN .framer-1wyzhrl, .framer-jssiN .framer-1t3o5ea, .framer-jssiN .framer-itynrh { height: 300px; position: relative; width: 400px; }",
	".framer-jssiN .framer-1pokmp6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 100%; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-jssiN .framer-1ohe3dd { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 475px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-jssiN .framer-4ijeku-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: -10px; top: 0px; z-index: 1; }",
	".framer-jssiN .framer-dvutxs, .framer-jssiN .framer-lqk0ha { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-jssiN .framer-13tlijn-container { flex: none; height: 480px; position: relative; width: 480px; }",
];
var FramerGmt8DuPBe = withCSS(Component, css, "framer-jssiN");
var stdin_default2 = FramerGmt8DuPBe;
FramerGmt8DuPBe.displayName = "mu_hang";
FramerGmt8DuPBe.defaultProps = {
	height: 1659,
	width: 1200,
};
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerGmt8DuPBe,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...Navigation3Fonts,
		...SlideshowFonts,
		...GoogleMapsFonts,
		...CalComFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mu-hang
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MuHangFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"3759d569955c51a9b80f5c98b643a1993e0a03ee7b7b017caee5d6624b0e79fe"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var mu_hang_default = ComponentWithRoot;
export { mu_hang_default as default };
